### ISSUE TITLE
WorldEdit not working...

### ISSUE THREAD

**Issue by Yuri6037** [ForgeEssentials/ForgeEssentialsMain#1250]
Everytim i act on server (ex : placing block, ...), the server throw a crash log saying that sk89q's worldedit has crashed.

It's an Index out of bounds exception, here is the log : 
[12:20:17] [permission persistence timer/INFO] [ForgeEssentials]: Saving permiss
ions...
janv. 16, 2015 12:20:15 PM com.sk89q.worldedit.util.eventbus.EventBus dispatch
Grave: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.

PlatformReadyEvent@1142bdd to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandl

er.java:75)
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187

)
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173)
        at com.sk89q.worldedit.forge.ForgeWorldEdit.serverStarted(ForgeWorldEdit

.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContain

er.java:513)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscribe

r.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(Sy

nchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.jav

a:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadContro

ller.java:208)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadControll

er.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscribe

r.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(Sy

nchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.jav

a:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadControl

ler.java:118)
        at cpw.mods.fml.common.Loader.serverStarted(Loader.java:752)
        at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHan

dler.java:283)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodE

ventHandler.java:58)
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandl

er.java:73)
        ... 32 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.sk89q.worldedit.forge.ForgePlatform.registerCommands(ForgePlatfor

m.java:156)
        at com.sk89q.worldedit.extension.platform.CommandManager.register(Comman

dManager.java:173)
        at com.sk89q.worldedit.extension.platform.Capability$2.initialize(Capabi

lity.java:53)
        at com.sk89q.worldedit.extension.platform.PlatformManager.choosePreferre

d(PlatformManager.java:181)
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlatform

Ready(PlatformManager.java:301)
        ... 38 more

**Comment by luacs1998** [comment]
Get latest worldedt dev build from builds.enginehub.org
