### ISSUE TITLE
On a fresh new world, there are no world borders, clients crash on playerMove

### ISSUE THREAD

**Issue by cri5ti** [ForgeEssentials/ForgeEssentialsMain#1256]
From a quick debug, it seems that the *world load* events are fired before the *server started* event.

* When server starts, each world loads first, and there is a check if a world border exists for that world, creating a default one otherwise.
* Then the *server started* (`FEModuleServerPostInitEvent`) event is fired which loads all the world borders, but it completely replaces the `borderMap` hashmap (essentially empty by default).

I think the regression happened here: https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/aea8d804fb6d172c3ca104a5b5dfb8d7ad2c725f#diff-65b8bb9236508584ed3209b5b64e4cc1L48, the old code merged the loaded borders.

For a quick fix, I've moved the world loading to a `FEModuleServerPreInitEvent` and that seems to work by loading the world borders before any world loading starts, but I'm new to Forge & ForgeEssentials and not sure what the implications are. 

I can provide a pull request if needed, but changes are minimal.

**Comment by luacs1998** [comment]
Give me the playermove crash log.

Walls of text and offering to fix code only helps so much *if we don't know what the problem is.*

**Comment by cri5ti** [comment]
Here's the exception:

```
[14:41:55] [Server thread/ERROR] [FML/]: Exception caught during firing event com.forgeessentials.util.events.PlayerMoveEvent@5edc9cf2:
java.lang.NullPointerException
	at com.forgeessentials.worldborder.ModuleWorldBorder.playerMove(ModuleWorldBorder.java:163) ~[ModuleWorldBorder.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_76_ModuleWorldBorder_playerMove_PlayerMoveEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at com.forgeessentials.util.events.ForgeEssentialsEventFactory.playerTickEvent(ForgeEssentialsEventFactory.java:32) [ForgeEssentialsEventFactory.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_97_ForgeEssentialsEventFactory_playerTickEvent_PlayerTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) [mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) [jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

And the complete log file: http://pastebin.com/NJkFaXVY

**Comment by halvors** [comment]
I can confirm this. Manuallt adding following lines to "FEData/json/WorldBorder/WORLD_0.json fixed the problem for me:

``
{
  "zone": "WORLD_0",
  "center": {
    "x": 0,
    "y": 64,
    "z": -500
  },
  "rad": 2048,
  "shapeByte": 2,
  "enabled": true
}
``
