### ISSUE TITLE
Player Can not Respawn!

### ISSUE THREAD

**Issue by Crutchie** [ForgeEssentials/ForgeEssentialsMain#1284]
So this only happens when i have forge essentials installed. When a player dies and tries to respawn they will get kicked with the error internal server error. Here is the log from the server when the error occurs.
````
[14:56:57] [User Authenticator #2/INFO]: UUID of player iTzCrutchie is 18208821-d564-48df-996b-fdae61bc1602
[14:56:58] [Server thread/INFO]: iTzCrutchie[/66.25.218.63:61640] logged in with entity id 590 at (1538.5, 109.0999984741211, 1976.5)
[14:56:58] [Server thread/INFO]: iTzCrutchie joined the game
[14:57:02] [Server thread/WARN]: Failed to handle packet for /66.25.218.63:61640
java.lang.NullPointerException
	at net.minecraft.server.management.ServerConfigurationManager.func_72356_a(ServerConfigurationManager.java:479) ~[oi.class:?]
	at com.forgeessentials.util.FunctionHelper.teleportPlayer(FunctionHelper.java:542) ~[FunctionHelper.class:?]
	at com.forgeessentials.teleport.util.RespawnHandler.doRespawn(RespawnHandler.java:99) ~[RespawnHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_632_RespawnHandler_doRespawn_PlayerRespawnEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerRespawnEvent(FMLCommonHandler.java:560) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72368_a(ServerConfigurationManager.java:473) ~[oi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:860) ~[nh.class:?]
	at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:50) ~[is.class:?]
	at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:8) ~[is.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[14:57:08] [Server thread/INFO]: iTzCrutchie lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[14:57:08] [Server thread/INFO]: iTzCrutchie left the game

**Comment by Crutchie** [comment]
I am using the latest forgeessentials beta5

**Comment by olee** [comment]
It seems you've set your spawn-point in a dimension that does not exist any more.
Try setting your spawn correctly again (you probably need to do that from console if you can't join the server any more.
You can run `/p test fe.internal.spawn` to see where the current spawn is set for you.
