### ISSUE TITLE
Kicks me out at login

### ISSUE THREAD

**Issue by hidemat** [ForgeEssentials/ForgeEssentialsMain#1295]
Hello,
I'm trying to do a test run on a local forge server with "forgeessentials-1.7.10-1.4.0-beta4-server" on it. That is the only mod installed on the server. My client has no mods. I'm using forge 10.13.2.1291 on both. But when i login, it kicks me out whenever I move. This is the the section of my server log that displays when i try to login and move:
````
[10:09:12] [User Authenticator #7/INFO]: UUID of player Hidemat is cac2466e-0521-48ee-99b5-fa461fd9ac01
[10:09:12] [Server thread/INFO]: Hidemat[/127.0.0.1:50180] logged in with entity id 706 at (-1.058500738265677, 72.58055397453333, -2.0203272489722384)
[10:09:12] [Server thread/INFO]: Hidemat joined the game
[10:09:13] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:50180
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
	at com.forgeessentials.worldborder.ModuleWorldBorder.playerMove(ModuleWorldBorder.java:163) ~[ModuleWorldBorder.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_37_ModuleWorldBorder_playerMove_PlayerMoveEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at com.forgeessentials.util.events.ForgeEssentialsEventFactory.playerTickEvent(ForgeEssentialsEventFactory.java:32) ~[ForgeEssentialsEventFactory.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_87_ForgeEssentialsEventFactory_playerTickEvent_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more
[10:09:13] [Server thread/INFO]: Hidemat lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[10:09:13] [Server thread/INFO]: Hidemat left the game

**Comment by olee** [comment]
Upgrade to [latest version](http://176.9.50.214:8080/job/ForgeEssentials/). This bug should have already been fixed.

**Comment by hidemat** [comment]
I downloaded the most recent version from mincraft.cursforge.com. Is there another website I need to be looking for?

**Comment by olee** [comment]
Did you even read my post?
I especially put the link in it for you.... T_T

**Comment by hidemat** [comment]
oh crap sorry XD. and thanks

**Comment by hidemat** [comment]
Question. Does this version include world edit integration tools?

**Comment by olee** [comment]
Yes, as any version - please join our IRC channel for questions like this.
