### ISSUE TITLE
server state crash scripting conflicting with scripting

### ISSUE THREAD

**Issue by kain184** [ForgeEssentials/ForgeEssentialsMain#1315]
[14:23:46] [Server thread/ERROR] [FML/]: Caught exception from ForgeEssentials
java.lang.RuntimeException: {FE-Module-Launcher} Scripting is conflicting with Scripting
	at com.forgeessentials.core.moduleLauncher.ModuleLauncher.preLoad(ModuleLauncher.java:56) ~[ModuleLauncher.class:?]
	at com.forgeessentials.core.ForgeEssentials.preInit(ForgeEssentials.java:141) ~[ForgeEssentials.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[14:23:46] [Server thread/WARN] [FML/]: Can't revert to frozen GameData state without freezing first.
having this error on my server needing a bit of help full log is https://dl.dropboxusercontent.com/u/49292585/fml-server-latest.log as pastbin says my file is to big

**Comment by helinus** [comment]
You should go over your mods folder and check for duplicates of all your mods, the log on your dropbox says you have two versions of Botania.

**Comment by kain184** [comment]
ok well that did fix that one but now it is thowing a diffrent set of errors. guess i am in search of more awnsers unless you can help me again  i threw the new file in will be  https://dl.dropboxusercontent.com/u/49292585/fml-server-latest.log i stink at reading logs sometimes and i am just frustrated right now so any help will be appreciated

**Comment by helinus** [comment]
The only bad thing in that log is AromaBackup derping

**Comment by kain184** [comment]
looked into the world file and saw it was all jacked up so i refreshed from a backup my guess is aroma backup broke it when stuff was freeking out. but now it just keeps loading and unloading the dimensions  i reupped the file if you would like to look if you can help

**Comment by helinus** [comment]
Your Botania version is 22 versions behind latest and please seek help elsewhere as this has nothing to do with FE
