### ISSUE TITLE
Permissions MySQL error after adding a user that FE hasn't seen

### ISSUE THREAD

**Issue by kerts93** [ForgeEssentials/ForgeEssentialsMain#1324]
After you set user's group for a user that FE hasn't seen, it throws this error message and clears fepermissions_user_permission table.

Using build #422 on jenkins (beta 6)
It starts repeating this message into the console:
````
[14:59:10] [permission persistence timer/INFO] [ForgeEssentials/]: Saving permissions...
[14:59:11] [permission persistence timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[14:59:11] [permission persistence timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.forgeessentials.permissions.persistence.SQLProvider.saveZonePermissions(SQLProvider.java:429)
[14:59:11] [permission persistence timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.forgeessentials.permissions.persistence.SQLProvider.save(SQLProvider.java:380)
[14:59:11] [permission persistence timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.forgeessentials.permissions.core.ZonedPermissionHelper.save(ZonedPermissionHelper.java:132)
[14:59:11] [permission persistence timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.forgeessentials.permissions.core.ZonedPermissionHelper$PersistenceTask.run(ZonedPermissionHelper.java:111)
[14:59:11] [permission persistence timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[14:59:11] [permission persistence timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.TimerThread.run(Timer.java:505)

**Comment by kerts93** [comment]
Full log: http://thesociety.eu/uploads/logsForBugReports/2015-03-07_ForgeEssentialsBug_fml-server-latest.log

**Comment by kerts93** [comment]
Just confirmed that adding player is not the only case, i was playing around in the world when it suddenly started saving permissions after every 2 seconds and same error appears (and again database field empy)

Image of console: http://i.imgur.com/wvAhdgA.png

**Comment by olee** [comment]
Hm this is interesting - ConcurrentModificationException.
We should check the permission-code for multi-threading.

**Comment by kerts93** [comment]
I just noticed that after restart other tables are also back to default.

**Comment by kerts93** [comment]
Same thing with H2_File

**Comment by olee** [comment]
Please try with latest build again and check, if it works now.
You might want to recreate your permission DB, too.
If you don't really need SQL permissions (for external access like webpages etc.), I also highly recommend you use flatfile instead.
It should be faster and is also easier to edit.
