### ISSUE TITLE
Backup Module

### ISSUE THREAD

**Issue by TeufelPenguin** [ForgeEssentials/ForgeEssentialsMain#1326]
The backup module is filling my hard drive.

Yes, I read the readme

**Comment by luacs1998** [comment]
You can delete backups manually. Or turn on autoremove (it's disabled by default).

**Comment by luacs1998** [comment]
Look in the god damned ForgeEssentials/Backups.cfg file, your life will be so much easier -.-

**Comment by TeufelPenguin** [comment]
The auto remove isn't working...  and I think I disabled the backups, guess I'll find out if my drive fills again.

**Comment by jrodder** [comment]
I read the readme, but I don't see any more documentation on removing them manually. Unless you literally mean I can just rm them from terminal without issue? My storage filled to completely full since I never changed the -1 default option on space allowed. Logs are full of errors saying:

[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.nio.file.DirectoryNotEmptyException: ForgeEssentials/Backups/TEST/DIM_80
[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at java.nio.file.Files.delete(Files.java:1079)
[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at com.forgeessentials.backup.AutoBackup.loopThroughFolder(AutoBackup.java:138)
[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at com.forgeessentials.backup.AutoBackup.checkMaxFBackupLifespan(AutoBackup.java:115)
[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at com.forgeessentials.backup.AutoBackup.run(AutoBackup.java:97)
[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at java.util.TimerThread.mainLoop(Timer.java:555)
[00:10:12] [Timer-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at java.util.TimerThread.run(Timer.java:505)
[00:10:12] [Timer-1/ERROR] [ForgeEssentials]: Could not delete file


I don't believe it's a permissions issue.

**Comment by Cuppycake** [comment]
Yes just RM them. I wrote a script to remove any that are older than 3 days.

**Comment by jrodder** [comment]
Thanks for the reply. I moved them out of the folder just in case, seems to be OK so far. It's just that readme is so ominous, and me not being a java guy and knowing what exactly the backup module is doing or needs to do....

**Comment by Cuppycake** [comment]
I don't use this module anymore just because I like my method now but when I did I just used the option to auto remove them. Worked perfectly.
