### ISSUE TITLE
Someone Please Help Me Understand This Bug - Occured After I Rebooted Server

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1359]
[18:41:03] [Server thread/ERROR] [FML]: 46: ASM: com.forgeessentials.chat.MailSy
stem@59957872 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLog
gedInEvent;)V
[18:41:03] [Server thread/ERROR] [FML]: HandshakeCompletionHandler exception
java.lang.NullPointerException
        at com.forgeessentials.util.UserIdent.getUsernameByUuid(UserIdent.java:3
05) ~[UserIdent.class:?]
        at com.forgeessentials.util.UserIdent.updateUsername(UserIdent.java:144)
 ~[UserIdent.class:?]
        at com.forgeessentials.api.permissions.Zone.updatePlayerIdents(Zone.java
:405) ~[Zone.class:?]
        at com.forgeessentials.permissions.core.ZonedPermissionHelper.playerLogi
n(ZonedPermissionHelper.java:311) ~[ZonedPermissionHelper.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_65_ZonedPermissionHe
lper_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandl
er.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[E
ventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHand
ler.java:550) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.initialize
ConnectionToPlayer(ServerConfigurationManager.java:180) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServe
rSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHands
hake(NetworkDispatcher.java:463) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.chann
elRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?
]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.chann
elRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?
]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChanne
lInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(Defau
ltChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:103) [MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMes
sageCodec.java:111) [MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(Defau
ltChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChanne
l.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FML
ProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java
:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:
165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
[18:41:03] [Server thread/ERROR] [FML]: There was a critical exception handling
a packet on channel FML
java.lang.NullPointerException
        at com.forgeessentials.util.UserIdent.getUsernameByUuid(UserIdent.java:3
05) ~[UserIdent.class:?]
        at com.forgeessentials.util.UserIdent.updateUsername(UserIdent.java:144)
 ~[UserIdent.class:?]
        at com.forgeessentials.api.permissions.Zone.updatePlayerIdents(Zone.java
:405) ~[Zone.class:?]
        at com.forgeessentials.permissions.core.ZonedPermissionHelper.playerLogi
n(ZonedPermissionHelper.java:311) ~[ZonedPermissionHelper.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_65_ZonedPermissionHe
lper_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandl
er.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[E
ventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHand
ler.java:550) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.initialize
ConnectionToPlayer(ServerConfigurationManager.java:180) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServe
rSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHands
hake(NetworkDispatcher.java:463) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.chann
elRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?
]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.chann
elRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?
]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChanne
lInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(Defau
ltChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMes
sageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(Defau
ltChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(Default
ChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChanne
l.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FML
ProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java
:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:
165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
[18:41:03] [Server thread/WARN]: Failed to handle packet for /10.0.0.12:49585
java.lang.NullPointerException
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FML
ProxyPacket.java:101) ~[FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java
:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:
165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
[18:41:04] [Server thread/INFO] [JustAnotherSpawner]: Passive Spawning entity ne
vermine.Sasquatch of type MONSTER at 133, 50, 282 (biomesoplenty.common.biome.ov
erridden.BiomeGenBOPPlains.Plains)
[18:41:04] [Server thread/INFO] [JustAnotherSpawner]: Passive Spawning entity ne
vermine.Sasquatch of type MONSTER at 131, 50, 281 (biomesoplenty.common.biome.ov
erridden.BiomeGenBOPPlains.Plains)
[18:41:04] [Server thread/INFO] [JustAnotherSpawner]: Passive Spawning entity ne
vermine.Sasquatch of type MONSTER at 133, 50, 281 (biomesoplenty.common.biome.ov
erridden.BiomeGenBOPPlains.Plains)
[18:41:04] [Server thread/INFO] [JustAnotherSpawner]: Passive Spawning entity ne
vermine.Sasquatch of type MONSTER at 135, 50, 282 (biomesoplenty.common.biome.ov
erridden.BiomeGenBOPPlains.Plains)

**Comment by luacs1998** [comment]
Update FE to latest build.

**Comment by luacs1998** [comment]
Assuming fixed - closing.
