### ISSUE TITLE
Exception thrown when sending incomplete command

### ISSUE THREAD

**Issue by Pyeroh** [ForgeEssentials/ForgeEssentialsMain#1365]
When I type in a command without the minimal number of parameters required, FE throw an exception.

Example with doas :
```
[15:13:59] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[15:13:59] [Server thread/ERROR]: Couldn't process command: 'doas'
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.forgeessentials.commands.admin.CommandDoAs.func_71515_b(CommandDoAs.java:54) ~[CommandDoAs.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:370) [lt.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

I didn't tested many commands, but I suppose this bug can be reproduced on every command, if it requires at least 1 parameter

**Comment by DPxKnightxZero** [comment]
Here try this mod it fixed my issue  https://drive.google.com/file/d/0B1fY2sKXiHd7WnhkVm1BTGhxWnM/view?usp=sharing

**Comment by Pyeroh** [comment]
Thank you for your reply, but I already have it ;)

**Comment by DPxKnightxZero** [comment]
Oh well that is new ... can I have the full crash log? I am curious to see if a different mod could be causing it.

**Comment by Pyeroh** [comment]
Here for you : http://pastebin.com/GycL0khT

**Comment by DPxKnightxZero** [comment]
Please remove fastcraft and optifine if you have it and try again. Tconstruct Natura and several others don't play nice with most mods ... also I can never get thaumcraft to play nice either the mod I now consider overrated. Remove those mods and try again also make sure your grabbing the latest release to the mods in your pack as well as WR-CBE and Treecapitar. Code chicken updates a lot and I recommend always using his beta to make sure you fix any inconsistencies.

**Comment by luacs1998** [comment]
Give me a list of all the commands you've tried which has this issue.

**Comment by Pyeroh** [comment]
burn, doas, irc, mail. These are the only commands that throw an exception (about 50 pages of commands with help)

**Comment by olee** [comment]
That's because of all these awefully written "parsers" (it's an insult to call these parsers) in the command handlers.
We should really fix some of these in the future.
Better use queues for arguments or [CommandParserArgs](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/util/CommandParserArgs.java)
