### ISSUE TITLE
Beta7 crash

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentialsMain#1398]
Hello,

I updated today ( I wasn't for some times ) to the jenkins beta7 and it always crash like this:

A problem occurred running the Server launcher.[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetExce[40/217]
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:606)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cpw/mods/fml/common/asm/transformers/EventSubscriptionTransformer.buildEvents(Lorg/objectweb/asm/tree/ClassNode;)Z @349: invokevirtual
  Reason:
    Type 'org/objectweb/asm/tree/VarInsnNode' (current frame, stack[1]) is not assignable to 'org/objectweb/asm/tree/AbstractInsnNode'
  Current Frame:
    bci: @349
    flags: { }
    locals: { 'cpw/mods/fml/common/asm/transformers/EventSubscriptionTransformer', 'org/objectweb/asm/tree/ClassNode', 'java/lang/Class', integer, integer, integer, 'java/lang/Clas
s', 'org/objectweb/asm/Type', 'org/objectweb/asm/Type', 'org/objectweb/asm/tree/MethodNode' }
    stack: { 'org/objectweb/asm/tree/InsnList', 'org/objectweb/asm/tree/VarInsnNode' }
  Bytecode:
    0000000: 2ab6 0057 b600 5d2b b400 6010 2f10 2eb6
    0000010: 0064 b600 6a4d 126c 2cb6 0070 9a00 0503
    0000020: ac03 3e03 3604 0336 0512 7203 2ab6 0057
    0000030: b600 5db8 0076 3a06 1906 b800 7c3a 072b
    0000040: b400 80b9 0086 0100 3a08 1908 b900 8c01
    0000050: 0099 0095 1908 b900 9001 00c0 0092 3a09
    0000060: 1909 b400 9412 96b6 001b 9900 2519 09b4
    0000070: 0099 b200 9d03 bd00 78b8 00a1 b600 1b99
    0000080: 0010 1909 b400 a507 7e07 a000 0504 3e19
    0000090: 09b4 0094 12a7 b600 1b99 0025 1909 b400
    00000a0: 9919 0703 bd00 78b8 00a1 b600 1b99 0011
    00000b0: 1909 b400 a504 7e04 a000 0604 3604 1909
    00000c0: b400 9412 a8b6 001b 9900 1b19 09b4 0099
    00000d0: b200 9d03 bd00 78b8 00a1 b600 1b99 0006
    00000e0: 0436 05a7 ff67 1d99 0028 1504 9a00 21bb
    00000f0: 00aa 59bb 00ac 59b7 00ad 12af b600 b32b
    0000100: b400 b4b6 00b3 b600 b8b7 00bb bf03 ac2b
    0000110: b400 60b8 00be 3a08 2bb4 00c1 bb00 c359
    0000120: 100a 12c5 1907 b600 c801 01b7 00cb b900
    0000130: ce02 0057 bb00 9259 12cf 0412 a8b2 009d
    0000140: 03bd 0078 b800 a101 01b7 00d2 3a09 1909
    0000150: b400 d6bb 00d8 5910 1903 b700 dbb6 00e0
    0000160: 1909 b400 d6bb 00e2 5911 00b7 1908 b600
    0000170: e512 a8b2 009d 03bd 0078 b800 a103 b700
    0000180: e8b6 00e0 1909 b400 d6bb 00ea 5911 00b1
    0000190: b700 ebb6 00e0 1505 9a00 0f2b b400 8019
    00001a0: 09b9 00ce 0200 57bb 0092 5912 cf07 1296
    00001b0: b200 9d03 bd00 78b8 00a1 0101 b700 d23a
    00001c0: 0919 09b4 00d6 bb00 d859 1019 03b7 00db
    00001d0: b600 e019 09b4 00d6 bb00 e259 1100 b719
    00001e0: 08b6 00e5 1296 b200 9d03 bd00 78b8 00a1
    00001f0: 03b7 00e8 b600 e019 09b4 00d6 bb00 ed59
    0000200: 1100 b22b b400 b412 c519 07b6 00c8 b700
    0000210: f0b6 00e0 bb00 f259 b700 f33a 0a19 09b4
    0000220: 00d6 bb00 f559 1100 c619 0ab7 00f8 b600
    0000230: e019 09b4 00d6 bb00 ea59 1100 b1b7 00eb
    0000240: b600 e019 09b4 00d6 190a b600 e019 09b4
    0000250: 00d6 bb00 fa59 0603 0103 01b7 00fd b600
    0000260: e019 09b4 00d6 bb00 ff59 1100 bb19 07b6
    0000270: 00e5 b701 02b6 00e0 1909 b400 d6bb 00ea
    0000280: 5910 59b7 00eb b600 e019 09b4 00d6 bb00
    0000290: d859 1019 03b7 00db b600 e019 09b4 00d6
    00002a0: bb00 e259 1100 b719 08b6 00e5 12a7 1907
    00002b0: 03bd 0078 b800 a103 b700 e8b6 00e0 1909
    00002c0: b400 d6bb 00e2 5911 00b7 1907 b600 e512
    00002d0: a8b2 009d 04bd 0078 5903 1907 53b8 00a1
    00002e0: 03b7 00e8 b600 e019 09b4 00d6 bb00 ed59
    00002f0: 1100 b32b b400 b412 c519 07b6 00c8 b700
    0000300: f0b6 00e0 1909 b400 d6bb 00ea 5911 00b1
    0000310: b700 ebb6 00e0 2bb4 0080 1909 b900 ce02
    0000320: 0057 bb00 9259 12cf 0412 a719 0703 bd00
    0000330: 78b8 00a1 0101 b700 d23a 0919 09b4 00d6
    0000340: bb00 ed59 1100 b22b b400 b412 c519 07b6
    0000350: 00c8 b700 f0b6 00e0 1909 b400 d6bb 00ea
    0000360: 5911 00b0 b700 ebb6 00e0 2bb4 0080 1909
    0000370: b900 ce02 0057 04ac                    
  Stackmap Table:
    append_frame(@33,Object[#89])
    full_frame(@74,{Object[#2],Object[#44],Object[#89],Integer,Integer,Integer,Object[#89],Object[#120],Object[#136]},{})
    append_frame(@143,Object[#146])
    same_frame(@190)
    chop_frame(@227,1)
    chop_frame(@230,1)
    same_frame(@269)
    same_frame(@271)
    append_frame(@423,Object[#120],Object[#146])

[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.getDeclaredConstructors0(Native Method)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.getConstructor0(Class.java:2885)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.newInstance(Class.java:350)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:
88)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModMana
ger.java:101)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:18:34] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 6 more

Thank you for your time.

**Comment by luacs1998** [comment]
Problem with fastcraft, remove it

**Comment by Ganjalf-Amsterdoom** [comment]
The mod still  does not boot and crash with fml sanity check error.

**Comment by luacs1998** [comment]
Post in #1449

**Comment by SpicyAngel** [comment]
Sorry i know this is not mine, but wanted to say thank you luacs1998 removing fastcraft with a simlar error helped me!
