### ISSUE TITLE
Player Logger Database

### ISSUE THREAD

**Issue by newborn1000** [ForgeEssentials/ForgeEssentialsMain#1408]
Hi Guys, 

I have an error with the Player Logger database which means it's not logging anything. whenever a member places a block (even vanilla blocks)

The error is very long but the first line about sums up the issue:

[10:31:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for c
olumn 'block' at row 1
[10:31:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4094)
[10:31:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
[10:31:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
[10:31:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
[10:31:45] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)

Issue seems to be related to mystcraft as it happens in Mystcraft worlds. However my guess is it'll happen in multiple situations when the data becomes too large for the field type.

**Comment by olee** [comment]
You are olding an old build - please update to latest version with completely new player logger.
