### ISSUE TITLE
Crash by BlockPortal mixin

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentialsMain#1413]
Hello,

this is what I get when starting my server with FE, if I remove FE everything works fine.

Thank you for your time.

````
java.lang.NullPointerException: Exception ticking world
	at net.minecraft.block.BlockPortal.func_150000_e(SourceFile:84)
	at net.minecraft.block.BlockFire.func_149726_b(BlockFire.java:306)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at net.minecraft.block.BlockStaticLiquid.func_149674_a(SourceFile:56)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````
EDIT by @olee: cut out unnecessary log part and but it into code block

**Comment by olee** [comment]
Looks like an issue with my patch to portals...
This bug happens immediately when you start the server, correct?

**Comment by olee** [comment]
I will close this for now as the issue has probably been solved by that fix.
If not, please report.
