### ISSUE TITLE
I am new to forge servers!!

### ISSUE THREAD

**Issue by slicksniperkills** [ForgeEssentials/ForgeEssentialsMain#1425]
So I want to start a forge server but every time I put FE into my server mods folder i get an error and it crashes. Even if its the only mod in the folder!! Please guy I need help. Heres the error log:

Last login: Mon Apr 20 21:52:32 on ttys001
Erics-MacBook-Pro:~ EricDaryn$ /Users/EricDaryn/Documents/FTB/modded/start.command ; exit;
[21:59:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[21:59:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[21:59:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[21:59:10] [main/INFO] [FML]: Forge Mod Loader version 7.10.112.1374 for Minecraft 1.7.10 loading
[21:59:10] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.10.2, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[21:59:10] [main/INFO] [FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.7.10-1.4.0-beta6-server.jar
[21:59:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:59:10] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
A problem occurred running the Server launcher.[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.reflect.InvocationTargetException
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.UnsupportedClassVersionError: com/forgeessentials/core/preloader/FELaunchHandler : Unsupported major.minor version 51.0
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName0(Native Method)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName(Class.java:249)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:59:10] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 6 more
logout

[Process completed]

**Comment by dougkwilson** [comment]
Try using Java 1.7 instead of 1.6.

**Comment by slicksniperkills** [comment]
My java is outdated? Ill see but the server does run without the FE mod

**Comment by slicksniperkills** [comment]
Nope same problem

**Comment by dougkwilson** [comment]
Did you update to 1.7 or 1.8? Post the new log please.

**Comment by slicksniperkills** [comment]
No It works mate, Mac os x Yosemite handles java differently. For web browsers and similar apps it uses the java we normally download. But for more "Api" environments like Minecraft it uses developer JDKs to run. So the java that I had for Minecraft was JDK 1.6

**Comment by slicksniperkills** [comment]
Now its 1.7

**Comment by slicksniperkills** [comment]
Look:

Last login: Mon Apr 20 22:12:09 on ttys001
/Users/EricDaryn/Documents/FTB/modded/start.command ; exit;
Erics-MacBook-Pro:~ EricDaryn$ /Users/EricDaryn/Documents/FTB/modded/start.command ; exit;
[22:21:14] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[22:21:15] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[22:21:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[22:21:15] [main/INFO] [FML]: Forge Mod Loader version 7.10.112.1374 for Minecraft 1.7.10 loading
[22:21:15] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_79, running on Mac OS X:x86_64:10.10.2, installed at /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
[22:21:15] [main/INFO] [FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.7.10-1.4.0-beta6-server.jar
[22:21:15] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:21:15] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
[22:21:15] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[22:21:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:21:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:21:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:21:16] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:21:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:21:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[22:21:17] [main/INFO] [LaunchWrapper]: Calling tweak class com.forgeessentials.core.preloader.FELaunchHandler
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:extractLibs:43]: [ForgeEssentials] Could not find library folder - will create new one and re-extract libraries.
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:70]: [ForgeEssentials] Something happened that shouldn't have happened. Trying to recover.
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:110]: [ForgeEssentials] Loaded 0 modules
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:133]: [ForgeEssentials] You are missing the following library files.
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:136]: com.mysql.jdbc.Driver
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:136]: org.pircbotx.PircBotX
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:136]: org.h2.Driver
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:138]: [ForgeEssentials] We will now re-extract the missing library files.
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:doActualExtract:148]: [ForgeEssentials] Extracting libraries
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:doActualExtract:165]: [ForgeEssentials] Now extracting file ForgeEssentials/
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:doActualExtract:165]: [ForgeEssentials] Now extracting file ForgeEssentials/lib/
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:doActualExtract:165]: [ForgeEssentials] Now extracting file ForgeEssentials/lib/pircbotx-1.9.jar
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:doActualExtract:165]: [ForgeEssentials] Now extracting file ForgeEssentials/lib/h2-1.3.175.jar
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:doActualExtract:165]: [ForgeEssentials] Now extracting file ForgeEssentials/lib/mysql-connector-java-5.1.22.jar
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:doActualExtract:165]: [ForgeEssentials] Now extracting file mods/
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:doActualExtract:165]: [ForgeEssentials] Now extracting file mods/worldedit-forge-mc1.7.10-6.0.2-SNAPSHOT-dist.jar
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:80]: [ForgeEssentials] Loaded library file /Users/EricDaryn/Documents/FTB/modded/ForgeEssentials/lib/h2-1.3.175.jar
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:80]: [ForgeEssentials] Loaded library file /Users/EricDaryn/Documents/FTB/modded/ForgeEssentials/lib/mysql-connector-java-5.1.22.jar
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:80]: [ForgeEssentials] Loaded library file /Users/EricDaryn/Documents/FTB/modded/ForgeEssentials/lib/pircbotx-1.9.jar
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:110]: [ForgeEssentials] Loaded 0 modules
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:133]: [ForgeEssentials] You are missing the following library files.
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:136]: com.mysql.jdbc.Driver
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:136]: org.pircbotx.PircBotX
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:136]: org.h2.Driver
[22:21:17] [main/INFO] [STDERR]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:checkLibs:138]: [ForgeEssentials] We will now re-extract the missing library files.
[22:21:17] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.FELaunchHandler:injectIntoClassLoader:49]: Force-reinjecting ForgeEssentials mod container
[22:21:17] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[22:21:17] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[22:21:18] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[22:21:20] [Server thread/INFO]: Starting minecraft server version 1.7.10
[22:21:20] [Server thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[22:21:20] [Server thread/INFO] [FML]: MinecraftForge v10.13.3.1374 Initialized
[22:21:20] [Server thread/INFO] [FML]: Replaced 183 ore recipies
[22:21:20] [Server thread/INFO] [FML]: Preloading CrashReport classes
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.World$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.World$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.World$3
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.World$4
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.chunk.Chunk$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$3
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.entity.Entity$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.entity.Entity$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.entity.EntityTracker$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.entity.player.InventoryPlayer$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$3
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$3
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$4
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$5
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.network.NetHandlerPlayServer$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.network.NetworkSystem$3
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$3
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$1
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$2
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$3
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$4
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$5
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$6
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$7
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$8
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$9
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.server.dedicated.DedicatedServer$3
[22:21:20] [Server thread/INFO] [FML]: 	net.minecraft.server.dedicated.DedicatedServer$4
[22:21:20] [Server thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[22:21:20] [Server thread/INFO] [FML]: Searching /Users/EricDaryn/Documents/FTB/modded/mods for mods
[22:21:21] [Server thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[22:21:21] [Server thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, ForgeEssentials, worldedit] at CLIENT
[22:21:21] [Server thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, ForgeEssentials, worldedit] at SERVER
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Check passed, it's all good to go!
[22:21:22] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[22:21:22] [Server thread/INFO] [FML]: Found 341 ObjectHolder annotations
[22:21:22] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Initializing ForgeEssentials version 1.4.0-beta6 (configDir = /Users/EricDaryn/Documents/FTB/modded/./ForgeEssentials)
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Build information: Build number is: 476, build hash is: 382f0d5
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Discovering and loading modules...
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Modules from ForgeEssentials--1.4.0-beta6 are being loaded
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Backups
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Permissions
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Tickets
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Requested to disable module PlayerLogger
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Economy
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Chat
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Teleport
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded WorldBorder
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded perftools
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Scripting
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded SignTools
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded AuthLogin
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Protection
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Afterlife
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Commands
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded WEIntegrationTools
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Multiworld
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded Remote
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Loaded ServerVote
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Registering configuration for FE module Afterlife
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Registering configuration for FE module AuthLogin
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module Backups
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module Chat
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module Commands
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Registering configuration for FE module Economy
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Registering configuration for FE module Multiworld
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Registering configuration for FE module Permissions
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module Protection
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Registering configuration for FE module Remote
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module Scripting
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module ServerVote
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Registering configuration for FE module SignTools
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module Teleport
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module Tickets
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module WEIntegrationTools
[22:21:22] [Server thread/INFO] [ForgeEssentials]: No configuration for FE module WorldBorder
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Registering configuration for FE module perftools
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Scripts are being read from /Users/EricDaryn/Documents/FTB/modded/./ForgeEssentials/Scripting
[22:21:22] [Server thread/INFO] [ForgeEssentials]: Discovering and loading FEMob data...
[22:21:22] [Server thread/INFO] [FML]: Applying holder lookups
[22:21:22] [Server thread/INFO] [FML]: Holder lookups applied
[22:21:22] [Server thread/INFO]: Loading properties
[22:21:22] [Server thread/INFO]: Default game type: SURVIVAL
[22:21:22] [Server thread/INFO]: Generating keypair
[22:21:22] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:21:22] [Server thread/INFO] [ForgeEssentials]: FEauth initialized. Enabled: false
[22:21:23] [Server thread/INFO] [ForgeEssentials]: Loading rules
[22:21:23] [Server thread/INFO] [ForgeEssentials]: No rules file found. Generating with default rules..
[22:21:23] [Server thread/INFO] [ForgeEssentials]: Completed generating rules file.
[22:21:23] [Server thread/INFO] [ForgeEssentials]: Generating RSA key pair...
[22:21:23] [Server thread/INFO] [ForgeEssentials]: RSA key pair made!
[22:21:23] [Server thread/INFO] [ForgeEssentials]: [Multiworld] Available world providers:
[22:21:23] [Server thread/INFO] [ForgeEssentials]: # 0:normal
[22:21:23] [Server thread/INFO] [ForgeEssentials]: # 1:nether
[22:21:23] [Server thread/INFO] [ForgeEssentials]: # -1:end
[22:21:23] [Server thread/INFO] [ForgeEssentials]: [Multiworld] Available world types:
[22:21:23] [Server thread/INFO] [ForgeEssentials]: # MULTIWORLD
[22:21:23] [Server thread/INFO] [ForgeEssentials]: # FLAT
[22:21:23] [Server thread/INFO] [ForgeEssentials]: # LARGEBIOMES
[22:21:23] [Server thread/INFO] [ForgeEssentials]: # DEFAULT
[22:21:23] [Server thread/INFO] [ForgeEssentials]: # AMPLIFIED
[22:21:23] [Server thread/INFO] [worldedit]: WorldEdit for Forge (version 6.0.2-SNAPSHOT) is loaded
[22:21:23] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[22:21:23] [Server thread/INFO]: Preparing level "world"
[22:21:23] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[22:21:24] [Server thread/INFO] [FML]: Applying holder lookups
[22:21:24] [Server thread/INFO] [FML]: Holder lookups applied
[22:21:24] [Server thread/INFO] [FML]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@43b9e4b4)
[22:21:24] [Server thread/INFO] [FML]: Loading dimension 1 (world) (net.minecraft.server.dedicated.DedicatedServer@43b9e4b4)
[22:21:24] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@43b9e4b4)
[22:21:24] [Server thread/INFO]: Preparing start region for level 0
[22:21:24] [Server thread/INFO]: Done (1.566s)! For help, type "help" or "?"
[22:21:25] [Server thread/WARN] [ForgeEssentials]: Unable to create FEData backup
[22:21:25] [Server thread/ERROR] [ForgeEssentials]: Error loading permissions: invalid path
[22:21:25] [Server thread/INFO] [ForgeEssentials]: Votifier connection handler initialized!
[22:21:25] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
[22:21:26] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
[22:21:36] [User Authenticator #1/INFO]: UUID of player slicksniperkills is 6d2adb7d-7233-4ae8-8bf6-73413c10c300
[22:21:36] [Netty IO #2/INFO] [FML]: Client protocol version 1
[22:21:36] [Netty IO #2/INFO] [FML]: Client attempting to join with 26 mods : OpenMods@0.6,<CoFH ASM>@000,OpenModsCore@0.6,iChunUtil@4.1.3,OpenBlocks@1.3,Forge@10.13.2.1291,CodeChickenCore@1.0.4.29,BigReactors@0.4.2A2,Natura@2.2.0,Morph@0.9.1,Mekanism@7.1.1,Waila@1.5.3a,FML@7.10.85.1291,mcp@9.05,CoFHCore@1.7.10R3.0.2,BiomesOPlenty@2.1.0,NotEnoughItems@1.0.4.90,McMultipart@1.1.1.320,ProjRed|Core@4.5.13.65,ForgeMicroblock@1.1.1.320,ProjRed|Illumination@4.5.13.65,ForgeMultipart@1.1.1.320,ProjRed|Exploration@4.5.13.65,MrTJPCoreMod@1.0.5.11,voxelmap@1.7.10,Mantle@1.7.10-0.3.2.jenkins184
[22:21:36] [Netty IO #2/INFO] [FML]: Attempting connection with missing mods [ForgeEssentials, worldedit] at CLIENT
[22:21:36] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[22:21:36] [Server thread/INFO]: slicksniperkills[/127.0.0.1:50741] logged in with entity id 2186 at (3.5, 66.0, 260.5)
[22:21:36] [Server thread/INFO]: slicksniperkills joined the game
[22:21:36] [Server thread/INFO]: Welcome slicksniperkills to the server!
[22:21:37] [Server thread/INFO] [ForgeEssentials]: Saving permissions...
[22:21:45] [Server thread/INFO]: [GUEST]<slicksniperkills> §rhi
[22:21:48] [Server thread/INFO]: slicksniperkills lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[22:21:48] [Server thread/INFO]: slicksniperkills left the game

**Comment by dougkwilson** [comment]
Dude. The server loaded just fine. Now you need to push all your client mods to the server.

**Comment by slicksniperkills** [comment]
I know mate I was showing you that it was fixed

**Comment by dougkwilson** [comment]
A simple "Thanks, that worked" would have sufficed.

**Comment by slicksniperkills** [comment]
Sorry mate

**Comment by luacs1998** [comment]
So everything's OK?

**Comment by slicksniperkills** [comment]
Yes mate thank you works perfectly
