### ISSUE TITLE
Crash on startup [modcompat]

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1456]
Mixin patching crashes on (linux) server startup ([full log](http://pastebin.com/WXrH6qJn)).
Only happens if FE is used together with some other mod / mods.
Still need to figure out which though.
Also the client with (nearly) the same mods seems to load correctly (on windows) for me.
````

[20:47:46] [main/DEBUG] [mixin/]: Mixing block.BlockPortal_01 into net.minecraft.block.BlockPortal
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.asm.ASMCore.writeWorld(ASMCore.java:1070)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.asm.ASMCore.transform(ASMCore.java:177)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cofh.asm.CoFHClassTransformer.transform(CoFHClassTransformer.java:38)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.TreeInfo.applyTransformers(TreeInfo.java:146)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.TreeInfo.loadClass(TreeInfo.java:102)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.TreeInfo.getClassNode(TreeInfo.java:73)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:868)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:253)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixinMethods(MixinTransformer.java:519)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixin(MixinTransformer.java:415)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:367)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:272)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.block.Block.func_149671_p(Block.java:298)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[20:47:46] [main/WARN] [mixin/]: Mixin failed applying mixins.forgeessentials.json:block.BlockPortal_01 -> net.minecraft.block.BlockPortal: org.spongepowered.asm.mixin.transformer.InvalidMixinException Unexpecteded error whilst applying the mixin class
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unexpecteded error whilst applying the mixin class
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixin(MixinTransformer.java:422) ~[forgeessentials-1.7.10-1.4.0-beta7-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:367) ~[forgeessentials-1.7.10-1.4.0-beta7-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:272) [forgeessentials-1.7.10-1.4.0-beta7-server.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) [?:1.7.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) [?:1.7.0_65]
	at net.minecraft.block.Block.func_149671_p(Block.java:298) [aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) [kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260) [MinecraftServer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.3.1395-1710ls-universal-luacspatch.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.3.1395-1710ls-universal-luacspatch.jar:?]
Caused by: java.lang.NullPointerException
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:253) ~[forgeessentials-1.7.10-1.4.0-beta7-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixinMethods(MixinTransformer.java:519) ~[forgeessentials-1.7.10-1.4.0-beta7-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixin(MixinTransformer.java:415) ~[forgeessentials-1.7.10-1.4.0-beta7-server.jar:?]
	... 21 more
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unexpecteded error whilst applying the mixin class
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixin(MixinTransformer.java:422)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:367)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:272)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.block.Block.func_149671_p(Block.java:298)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:253)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixinMethods(MixinTransformer.java:519)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixin(MixinTransformer.java:415)
[20:47:46] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 21 more
````

**Comment by olee** [comment]
Solved... somehow
