### ISSUE TITLE
Unable to start server after updating to FE beta 6

### ISSUE THREAD

**Issue by CourtArtanis** [ForgeEssentials/ForgeEssentialsMain#1500]
[LaunchWrapper/]: Unable to launch
java.lang.RuntimeException: java.lang.ClassNotFoundException: cpw.mods.fml.common.asm.FMLSanityChecker
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:130) ~[forgeserver.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forgeserver.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forgeserver.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.asm.FMLSanityChecker
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_79]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:118) ~[forgeserver.jar:?]
	... 8 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.objectweb.asm.ClassReader.accept(Lorg/objectweb/asm/ClassVisitor;I)V" the class loader (instance of net/minecraft/launchwrapper/LaunchClassLoader) of the current class, cpw/mods/fml/common/asm/transformers/SideTransformer, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for resolved class, org/objectweb/asm/ClassReader, have different Class objects for the type accept used in the signature
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:42) ~[forgeserver.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_79]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:118) ~[forgeserver.jar:?]
	... 8 more

I only get this after adding beta6, the error doesn't appear when I drop back to beta5.
Using Forge1403 and Java 8, but I also get the error with Java 7

**Comment by liach** [comment]
Use newest build on Jenkins.

**Comment by CourtArtanis** [comment]
That seemed to do the trick, thanks :)

**Comment by luacs1998** [comment]
Fixed?

**Comment by CourtArtanis** [comment]
Yes sorry @luacs1998 that fixed that issue.
Cheers
