### ISSUE TITLE
Command Block crash - Crash Report Below:

### ISSUE THREAD

**Issue by doglover129** [ForgeEssentials/ForgeEssentialsMain#1531]
````
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/24/15 9:06 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.forgeessentials.util.BlockSaveable.<init>(BlockSaveable.java:32)
	at com.forgeessentials.commands.util.TickTaskPulseHelper.tick(TickTaskPulseHelper.java:32)
	at com.forgeessentials.util.tasks.TaskRegistry.onTick(TaskRegistry.java:128)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_TaskRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.8.0-36-generic
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 617271864 bytes (588 MB) / 990380032 bytes (944 MB) up to 990380032 bytes (944 MB)
	JVM Flags: 3 total; -Xmx1024M -Xms1024M -Xss2M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 9 mods loaded, 9 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeEssentials{1.4.0-beta7} [Forge Essentials] (forgeessentials-1.7.10-1.4.0-beta7-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	worldedit{6.0.2-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.0.2-SNAPSHOT-dist.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeEssentials: Build information: Build number is: 492, Build hash is: 7781428, Modules loaded: Afterlife, AuthLogin, Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, ServerVote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, perftools
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [EntityPlayerMP['USERNAME REMOVED FOR PRIVACY'/436, l='world', x=397.16, y=81.00, z=198.86]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by olee** [comment]
It's not command block but some kind of "pulse" thing.
Seems that thing places and removes a redstone block somewhere repeatedly like a timer.

@luacs1998 I vote for removing this from FE!
This is clearly a game content feature and FE should not be responsible for doing things like that.

**Comment by doglover129** [comment]
Thank you, after sending this information onto my host support, they sent me to you. I believe you are correct in the reds tone situation, and will look into it further.

**Comment by olee** [comment]
Just update to latest version of FE from http://ci.forgeessentials.com/job/ForgeEssentials/
There will be no more crash with this then.
