### ISSUE TITLE
[Protection] Crashes / issues by mods modifying world with FakePlayers

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1548]
Game crashes if for example an OpenBlocks block placer tries to place a block in a world that has the `fe.protection.gamemode = creative` permission set.

But not only that - there are probably some other issues for example if a FakePlayer would be used in a place event without setting it's location properly.

(Reported by Caitlyn on IRC)

````
java.lang.NullPointerException: Exception ticking world
	at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:942)
	at com.forgeessentials.util.OutputHandler.chatColored(OutputHandler.java:62)
	at com.forgeessentials.util.OutputHandler.chatError(OutputHandler.java:74)
	at com.forgeessentials.protection.ProtectionEventHandler.playerInteractEvent(ProtectionEventHandler.java:328)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_758_ProtectionEventHandler_playerInteractEvent_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
	at openmods.fakeplayer.OpenModsFakePlayer.rightClick(OpenModsFakePlayer.java:115)
	at openmods.fakeplayer.OpenModsFakePlayer.equipWithAndRightClick(OpenModsFakePlayer.java:84)
	at openblocks.common.tileentity.TileEntityBlockPlacer$1.usePlayer(TileEntityBlockPlacer.java:87)
	at openmods.fakeplayer.FakePlayerPool$1.usePlayer(FakePlayerPool.java:30)
	at openmods.fakeplayer.FakePlayerPool$1.usePlayer(FakePlayerPool.java:27)
	at openmods.fakeplayer.FakePlayerPool$WorldPool.executeOnPlayer(FakePlayerPool.java:50)
	at openmods.fakeplayer.FakePlayerPool.executeOnPlayer(FakePlayerPool.java:79)
	at openmods.fakeplayer.FakePlayerPool.executeOnPlayer(FakePlayerPool.java:74)
	at openblocks.common.tileentity.TileEntityBlockPlacer.placeBlock(TileEntityBlockPlacer.java:84)
	at openblocks.common.tileentity.TileEntityBlockPlacer.func_145842_c(TileEntityBlockPlacer.java:59)
	at openmods.block.OpenBlock.func_149696_a(OpenBlock.java:311)
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:968)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:955)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:196)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````

**Comment by olee** [comment]
With the above fix, it cannot crash any more, but there still might be improvements needed on FakePlayer handling.
