### ISSUE TITLE
Linus Server won't start

### ISSUE THREAD

**Issue by Destroyer4LP** [ForgeEssentials/ForgeEssentialsMain#1562]
My Linus Server won't start. With ForgeEssentials beta 6 works all fin but with Beta 7not.
The Log:
*EDIT by olee: Put your logs into code brackets and properly format them!!!!!*
````
14:01:07
 CONSOLE:
[LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
14:01:07
 CONSOLE:
[LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
14:01:07
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
14:01:07
 CONSOLE:
[FML]: Forge Mod Loader version 7.10.130.1395 for Minecraft 1.7.10 loading
14:01:07
 CONSOLE:
[FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_71, running on Linux:amd64:3.14.17-nitradoV3-MC-300-nH-dP-a, installed at /games/sources/files/jre1.7.0_71_64bit
14:01:07
 CONSOLE:
[FML]: FML has detected several badly downloaded jar files, which have been named as zip files. You probably need to download them again, or they may not work properly
14:01:07
 CONSOLE:
[FML]: Problem file : Improving Minecraft-1.6.jar.zip
14:01:07
 CONSOLE:
[FML]: [AppEng] Core Init
14:01:07
 CONSOLE:
[FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of ForgeMultipart, 1.1.0.310 is newer than request 1.1.0.309
14:01:09
 CONSOLE:
[FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FastCraft-core]: FastCraft loading...
14:01:09
 CONSOLE:
[FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.7.10-1.4.0-beta7-server.jar
14:01:09
 CONSOLE:
[FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FML]: The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FML]: The coremod remoteio.core.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
14:01:09
 CONSOLE:
[LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
14:01:09
 CONSOLE:
[LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
14:01:09
 CONSOLE:
[LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
14:01:10
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
14:01:10
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
14:01:10
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:12
 CONSOLE:
[FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
14:01:12
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:12
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:12
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:12
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:12
 CONSOLE:
[Aroma1997Core]: Finished data injection.
14:01:12
 CONSOLE:
[Aroma1997Core]: Finished data injection.
14:01:12
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:12
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:13
 CONSOLE:
[FastCraft-core]: ColoredLights was not detected.
14:01:13
 CONSOLE:
[FastCraft-core]: ShadersMod was not detected.
14:01:13
 CONSOLE:
[FastCraft-core]: Optifine was not detected.
14:01:13
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:13
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:13
 CONSOLE:
[IC2-core]: Loaded library EJML-core-0.26.jar.
14:01:13
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:13
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
14:01:14
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
14:01:14
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
14:01:14
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:14
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:14
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:14
 CONSOLE:
[RemoteIO:ASM]: Adding transformer for: [net.minecraft.client.renderer.Tessellator]
14:01:14
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:14
 CONSOLE:
[LaunchWrapper]: Calling tweak class com.forgeessentials.core.preloader.FELaunchHandler
14:01:14
 CONSOLE:
[STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:83]: [ForgeEssentials] Loaded library file /games_0/ni620801_1/ftproot/minecraftotherpacks/ForgeEssentials/lib/mysql-connector-java-5.1.22.jar
14:01:14
 CONSOLE:
[STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:83]: [ForgeEssentials] Loaded library file /games_0/ni620801_1/ftproot/minecraftotherpacks/ForgeEssentials/lib/h2-1.3.175.jar
14:01:14
 CONSOLE:
[STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:83]: [ForgeEssentials] Loaded library file /games_0/ni620801_1/ftproot/minecraftotherpacks/ForgeEssentials/lib/pircbotx-1.9.jar
14:01:14
 CONSOLE:
[STDOUT]: [com.forgeessentials.core.preloader.classloading.FEClassLoader:runClassLoad:113]: [ForgeEssentials] Loaded 0 modules
14:01:14
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
14:01:14
 CONSOLE:
[STDOUT]: [cofh.asm.PCCAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
14:01:15
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
14:01:15
 CONSOLE:
[LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
14:01:15
 CONSOLE:
[LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
14:01:15
 CONSOLE:
[LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
14:01:15
 CONSOLE:
[LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
14:01:16
 CONSOLE:
[FastCraft-core]: 1 / 19 applied
14:01:17
 CONSOLE:
code is OBFUSCATED
14:01:17
 CONSOLE:
net.minecraft.world.WorldServer [ mt ] with checksum 809C9966D9959719D330E716BCA614B2
14:01:17
 CONSOLE:
injection in b ()V
14:01:17
 CONSOLE:
injection in b ()V
14:01:17
 CONSOLE:
[FastCraft-core]: 2 / 19 applied
14:01:17
 CONSOLE:
cpw.mods.fml.common.FMLCommonHandler with checksum 9D07ABF40E8390189AB4D1D4CAA86BAB
14:01:17
 CONSOLE:
injection in onPreServerTick ()V
14:01:17
 CONSOLE:
injection in onPostServerTick ()V
14:01:17
 CONSOLE:
injection in onPreWorldTick (Lahb;)V
14:01:17
 CONSOLE:
injection in onPostWorldTick (Lahb;)V
14:01:17
 CONSOLE:
injection mode to FORGE
14:01:17
 CONSOLE:
net.minecraft.world.World [ ahb ] with checksum B842EC784132866EFEC5CAD71366A37F
14:01:17
 CONSOLE:
World.updateEntities()...
14:01:17
 CONSOLE:
injection in h ()V
14:01:17
 CONSOLE:
injection in h ()V
14:01:17
 CONSOLE:
injection in h ()V
14:01:17
 CONSOLE:
injection in h ()V
14:01:18
 CONSOLE:
[STDERR]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1692]: Potential problem: Galacticraft did not complete injection of bytecode into: oi (4 / 6)
14:01:18
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: sv (1 / 1)
14:01:18
 CONSOLE:
[FastCraft-core]: 3 / 19 applied
14:01:18
 CONSOLE:
[LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
14:01:18
 CONSOLE:
[STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: xk (1 / 1)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: asm error net.minecraft.entity.Entity =b7U07#Q6b'KV9b3K)b$I]bPU)cY#H3<Bc$N6]GH[c` dr =bGSN4b8?^G@3I(.RYbSX^<X7_b2KTc9^*c:YTb0S43 2 1
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at fastcraft.asm.FastCraftTransformer.transform(F:229)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.TreeInfo.applyTransformers(TreeInfo.java:147)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.TreeInfo.loadClass(TreeInfo.java:96)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.TreeInfo.getClassNode(TreeInfo.java:59)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1355)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformFieldNode(MixinTargetContext.java:310)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:242)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMethods(MixinApplicator.java:284)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:198)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:181)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:552)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:524)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:360)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:101)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.ClassLoader.loadClass(Unknown Source)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.ClassLoader.loadClass(Unknown Source)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.block.Block.func_149671_p(Block.java:298)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.reflect.Method.invoke(Unknown Source)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.reflect.Method.invoke(Unknown Source)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
14:01:19
 CONSOLE:
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
14:01:19
 CONSOLE:
[mixin]: Mixin failed applying mixins.forgeessentials.json:block.BlockPortal_01 -> net.minecraft.block.BlockPortal: org.spongepowered.asm.mixin.transformer.InvalidMixinException Unexpecteded error whilst applying the mixin class
14:01:19
 CONSOLE:
error whilst applying the mixin class

**Comment by luacs1998** [comment]
Add -Dfastcraft.asm.permissive=true to launch args. If not remove fastcraft for now and wait for @sfplayeer1 to release a newer version.

**Comment by sfPlayer1** [comment]
Or use the test version from the end of the fastcraft thread..

**Comment by Destroyer4LP** [comment]
Thanks
