### ISSUE TITLE
/home across DIMs causing NullPointerException

### ISSUE THREAD

**Issue by Kellador** [ForgeEssentials/ForgeEssentialsMain#1570]
Trying to /home across DIMs especially from the main world to another sometimes causes following error:
```
[Server thread/ERROR]: Couldn't process command: 'home'
java.lang.NullPointerException
	at com.forgeessentials.core.misc.TeleportHelper.canTeleportTo(TeleportHelper.java:120) ~[TeleportHelper.class:?]
	at com.forgeessentials.core.misc.TeleportHelper.doTeleport(TeleportHelper.java:129) ~[TeleportHelper.class:?]
	at com.forgeessentials.core.misc.TeleportHelper.teleport(TeleportHelper.java:102) ~[TeleportHelper.class:?]
	at com.forgeessentials.teleport.CommandHome.processCommandPlayer(CommandHome.java:37) ~[CommandHome.class:?]
	at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.func_71515_b(ForgeEssentialsCommandBase.java:69) ~[ForgeEssentialsCommandBase.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```
It seems to resolve itself once you teleport to the DIM through other means.
Wether the destination DIM is being loaded or not doesn't seem to affect the occurrence of this.
This is using build #730.

**Comment by luacs1998** [comment]
I'm not sure what to classify what this as.

On one hand, it's a bug, because something isn't being done properly.

On the other hand, it's a feature, because you can have one home per dimension (I think?)

**Comment by olee** [comment]
Fixed by https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/4b2ba9ddeabdbf920076020d695cf7f7af758643
