### ISSUE TITLE
warning spam

### ISSUE THREAD

**Issue by rebeldev** [ForgeEssentials/ForgeEssentialsMain#1571]
Whenever an autonamous activator is placed in the world I begin to get the following spam in the server log:
````
java.lang.NullPointerException
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) [SimpleNetworkWrapper.class:?]
	at com.forgeessentials.util.selections.SelectionHandler.sendUpdate(SelectionHandler.java:34) [SelectionHandler.class:?]
	at com.forgeessentials.compat.worldedit.CUIComms.serverTick(CUIComms.java:55) [CUIComms.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_916_CUIComms_serverTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[11:57:36] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
````
My guess is this is due to the autonamous activator creating a sort of psuedo client connection in order to function as a player and forge essentials is trying to send CUI updates to this psuedo client.  It is reproducable,  Simply place an autonamous activator in the world and give it power, the spam will start instantly and will not stop until the activator is removed.  I have not tried other block placers but I suspect they may would cause the same issue.

**Comment by olee** [comment]
Seems like it tries to send a net message to a non-existing client.
Should be easy to fix -> @luacs1998

**Comment by luacs1998** [comment]
First off, I have a feeling autonomous activators are either hacking things or doing things badly. If you need to do things using a fake player then instantiate a FakePlayer.

Secondly, from inspection of the code, everything seems to be done correctly by us (checking if player has FEClient, player != null, etc).

For now, I'm marking this as modcompat unless I can either 1) talk to the mod author or 2) see some sources from them.

**Comment by luacs1998** [comment]
Try build 736 - I just committed a check to make sure packets weren't being sent to FakePlayers.

**Comment by rebeldev** [comment]
latest build has corrected the issue.  Thanks so much luacs1998.
