### ISSUE TITLE
Scripting/Pattern Command Not Working

### ISSUE THREAD

**Issue by RustyJP** [ForgeEssentials/ForgeEssentialsMain#1582]
Using Forge Essentials on crackpack forge server, while trying the /god example script, server posts error: an unknown error occured while attempting to perform this command

![image](https://cloud.githubusercontent.com/assets/12912890/8185116/4c558b84-143a-11e5-9cf8-5dabec09a598.png)

The server console reads: 
```
[15:13:36] [Server thread/ERROR]: Couldn't process command: 'god'
java.lang.NullPointerException
        at com.forgeessentials.scripting.pattern.PatternParser.add(PatternParser.java:36) ~[PatternParser.class:?]
        at com.forgeessentials.scripting.command.PatternCommand.processCommand(PatternCommand.java:107) ~[PatternCommand.class:?]
        at com.forgeessentials.scripting.command.PatternCommand.func_71515_b(PatternCommand.java:96) ~[PatternCommand.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)[li.class:?]
```
I am wanting to make my own command scripts, but can't as they don't seem to be working.
Is this bug or a server side error? Anyone know whats going on?

**Comment by olee** [comment]
Ouch... this was really a stupid mistake.
It seems I changed some code there without even properly checking it...
The pattern commands should work again now.

Also if you want to use some more features / functions in these commands, just tell me here.
They are quite easy to add and I believe there are probably many functions that would be nice to have. For example something like `setblock` or so...

**Comment by RustyJP** [comment]
Is it possible to bind an /effect command to something like /v, as vanish isn't working right now?

**Comment by olee** [comment]
Please open a new issue for questions unrelated to this PatternCommand problem :wink:
