### ISSUE TITLE
server error on startup (Linux Debian)

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1589]
hey guys! we love this project and launch a new dedicated linux server.
now we get this error during start, without forgeessentials the server starts normal:
any ideas ? thanks in advance
```
[13:27:15] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [server-forge.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [server-forge.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/util/FakePlayer
	at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.util.FakePlayer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayerMP
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_80]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_80]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.player.EntityPlayerMP de90c246 dr b656625f 3 1
	at fastcraft.asm.FastCraftTransformer.transform(F:251) ~[fastcraft-1.21.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_80]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260) ~[MinecraftServer.class:?]
	... 12 more

**Comment by olee** [comment]
Remove fastcraft or look at other related issues already posted here:
#1351 
#1386 
#1410 
#1497 
#1423 
....
