### ISSUE TITLE
/help causes client to disconnect from server

### ISSUE THREAD

**Issue by whocares0101** [ForgeEssentials/ForgeEssentialsMain#1594]
Using the /help command causes the client to disconnect.
It would seem the worldboder help entry is causing this, should be on one of the last pages.
FE (beta 8 build 752)

```
[10:31:50] [Netty Client IO #4/ERROR] [FML/]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"clickEvent":{"action":"suggest_command","value":"/worldborder "}} into a Component
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263) ~[ByteToMessageDecoder.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: com.google.gson.JsonParseException: Don't know how to turn {"clickEvent":{"action":"suggest_command","value":"/worldborder "}} into a Component
	at net.minecraft.util.IChatComponent$Serializer.deserialize(SourceFile:74) ~[fk.class:?]
	at net.minecraft.util.IChatComponent$Serializer.deserialize(SourceFile:29) ~[fk.class:?]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[Gson.class:?]
	at net.minecraft.util.IChatComponent$Serializer.func_150699_a(SourceFile:176) ~[fk.class:?]
	at net.minecraft.network.play.server.S02PacketChat.func_148837_a(SourceFile:28) ~[gj.class:?]
	at net.minecraft.util.MessageDeserializer.decode(SourceFile:40) ~[ez.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232) ~[ByteToMessageDecoder.class:?]
	... 16 more
```

**Comment by olee** [comment]
This is weird - it's seems the click-event is causing that problem...
