### ISSUE TITLE
cant create end world

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1597]
if i create a world with end provider the server crashes imediantly and everytime if somebody tries to enter the new end.

**Comment by olee** [comment]
1. Please confirm that it is the multiworld module that you are talking about
 2. Which command did you use to create the world?
 3. Are you using the latest version (as long as it is beta8 it should not matter which build)
 4. **Crash log!!!!!!!!"

**Comment by jogi01** [comment]
sry youre right!
i created it with multiworld, /create end end default
i use the latest dev builds
crash log:

java.lang.NullPointerException: Exception ticking world
	at codechicken.lib.world.WorldExtension.unloadChunk(WorldExtension.java:52)
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkUnLoad(WorldExtensionManager.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_878_WorldExtensionEventHandler_onChunkUnLoad_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:941)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:342)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.lib.world.WorldExtension.unloadChunk(WorldExtension.java:52)
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkUnLoad(WorldExtensionManager.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_878_WorldExtensionEventHandler_onChunkUnLoad_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:941)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:342)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 1 Drop: 1
	Level seed: -6989885749473596033
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,50,0), Chunk: (at 0,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6705 game time, 6705 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by luacs1998** [comment]
This seems to be a CCC/CCL crash - I probably need to look through sources.

**Comment by jogi01** [comment]
creating a new end was a try to workaround issue 1596 because there is no return from the normal end to the overworld. /back doesnt work and /spawn too. every teleport ends in the void..

**Comment by olee** [comment]
@luacs1998 that line you pointed at
CCL should simply add a null-check - will you do a PR?
