### ISSUE TITLE
dynanism table

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1599]
i use latest dev builds
if i put an axe into the table and start the simulation of left or right click the server crashes until you delete the block with mcedit

crashlog:
```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 6/22/15 8:11 PM
Description: Ticking block entity

java.lang.ClassCastException: thaumic.tinkerer.common.block.tile.tablet.TabletFakePlayer cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at com.forgeessentials.api.UserIdent.getPlayerMP(UserIdent.java:275)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.checkUserPermission(ZonedPermissionHelper.java:914)
	at com.forgeessentials.protection.ProtectionEventHandler.attackEntityEvent(ProtectionEventHandler.java:104)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_725_ProtectionEventHandler_attackEntityEvent_AttackEntityEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1185)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.swingHit(TileAnimationTablet.java:165)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.func_145845_h(TileAnimationTablet.java:114)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by luacs1998** [comment]
Ugggh, more fakeplayer problems...

**Comment by olee** [comment]
Hm I thought I covered all cases...
Anyway that one is Thaumic Tinkerer's fault for doing something as stupid as using a custom EntityPlayer for these actions instead of a proper FakePlayer.
I can fix FE crashing because of that, but that will **prevent any permissions on these actions from being checked!**

**Comment by luacs1998** [comment]
Do they have an issue tracker? File a bug report, it's an issue on their end.

**Comment by olee** [comment]
Sadly this is something that is not easy to change, so they won't take action which I can understand.
