### ISSUE TITLE
Portal mixin crash

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1616]
Seems a blaze shot a player in the nether, destroying the nether portal.

```
java.lang.NullPointerException: Exception while updating neighbours
	at net.minecraft.block.BlockPortal.func_149695_a(SourceFile:158)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:652)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.block.BlockFire.func_149726_b(BlockFire.java:310)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at net.minecraft.entity.projectile.EntitySmallFireball.func_70227_a(SourceFile:62)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(SourceFile:141)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.c.p.a(F:19)
	at fastcraft.Hooks.aq(F:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Full crash: https://gist.github.com/olee/b7c96fab42fb0776d611

**Comment by NitroxydeX** [comment]
So. Here with Informations on it: There where two blazes directly at the portal. Screenshot from the portal:

![2015-07-01_20 06 41](https://cloud.githubusercontent.com/assets/9305576/8461473/267ae356-202d-11e5-86df-5fe67782743f.png)

Was on the Server without FE to get this fckn Blazes away from there. :D

**Comment by liach** [comment]
Why `BlockPortal_01` is a subclass of `BlockPortal` not `Block`? On the mixin wiki it says they should have the same superclass...

**Comment by luacs1998** [comment]
Seems like the BlockPortal mixin needs reviewing - doing it now.

**Comment by olee** [comment]
Ok I disabled the portal mixin of ForgeEssentials for now.
This will remove all related crashes, however it removes the portal rendering tweak (which was not very important anyway...).
Will fix this if I have some time again...

**Comment by olee** [comment]
Continued in #1579
