### ISSUE TITLE
Ticking block entity FakePlayer crashing issue with anceint warfare?

### ISSUE THREAD

**Issue by robertm1771** [ForgeEssentials/ForgeEssentialsMain#1622]
using build 783 assuming I get that when downloading from Jenkins link on that build :)

While I know they have a problem they need to fix crashing still should be prevented. as in #1599

Thanks
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/10/15 1:52 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.server.management.UserListOps.func_152699_b(SourceFile:39)
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
	at net.minecraft.server.management.UserList.func_152692_d(SourceFile:85)
	at net.minecraft.server.management.ServerConfigurationManager.func_152596_g(ServerConfigurationManager.java:717)
	at com.forgeessentials.api.permissions.ServerZone.getAdditionalPlayerGroups(ServerZone.java:317)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:372)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.checkUserPermission(ZonedPermissionHelper.java:947)
	at com.forgeessentials.protection.ProtectionEventHandler.breakEvent(ProtectionEventHandler.java:215)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_943_ProtectionEventHandler_breakEvent_BreakEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.shadowmage.ancientwarfare.core.util.BlockTools.canBreakBlock(BlockTools.java:399)
	at net.shadowmage.ancientwarfare.automation.tile.worksite.TileWorksiteBoundedInventory.harvestBlock(TileWorksiteBoundedInventory.java:62)
	at net.shadowmage.ancientwarfare.automation.tile.worksite.WorkSiteCropFarm.processWork(WorkSiteCropFarm.java:196)
	at net.shadowmage.ancientwarfare.automation.tile.worksite.TileWorksiteBase.func_145845_h(TileWorksiteBase.java:179)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by olee** [comment]
Should be fixed with https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/20574e10f7f3442885e3eaed12aaf3e2f745abf7
Report if you still get the problem after updating to latest version.

**Comment by Alaberti** [comment]
Using version 1.4.3.955, I have this same issue.

http://pastebin.com/raw.php?i=2NRTwEjg

**Comment by liach** [comment]
`at net.shadowmage.ancientwarfare.core.util.BlockTools.canBreakBlock(BlockTools.java:388)`
Bad code from ancientwarfare I think.

**Comment by luacs1998** [comment]
Doesn't seem to be fixed.

**Comment by olee** [comment]
AncientWarefare fucked up.
They use a `GameProfile` with a `null` UUID:
https://github.com/shadowmage45/AncientWarfare2/blob/e2e4f032d32075bc209fa113f42cb49b21f3cb55/src/main/java/net/shadowmage/ancientwarfare/core/proxy/CommonProxyBase.java#L30

That's an issue they need to fix, but I can add a safeguard in FE for fails like this.

**Comment by olee** [comment]
https://github.com/shadowmage45/AncientWarfare2/issues/389

**Comment by olee** [comment]
This fix at least prevents FE from crashing and should make it work somehow.
Still in the end this is a serious issue they need to fix on their side.
