### ISSUE TITLE
ForgeEssentials 1.4.0 release crash start on Forge 10.13.4.1448 for minecraft 1.7.10

### ISSUE THREAD

**Issue by shadowc** [ForgeEssentials/ForgeEssentialsMain#1634]
Sorry if I'm missing info, I can try to research more if you tell me what to do. Thanks!
````
[17:21:39] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/util/FakePlayer
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class
:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.util.Fake
Player
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayerMP
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_60]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_60]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_60]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class
:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityP
layerMP
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_60]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_60]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_60]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260) ~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.player.EntityPlayerMP de90c246 dr b656625f 3 1
        at fastcraft.asm.FastCraftTransformer.transform(F:251) ~[fastcraft-1.21.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_60]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_60]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0
_60]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:182) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class
:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more

**Comment by olee** [comment]
Do you have fastcraft installed? Also does this really not happen, if FE is not installed?
This error does not seem to be related in any way to FE to me

**Comment by shadowc** [comment]
I do have FastCraft installed, and yes, it really does not happen. Server starts as soon as I remove ForgeEssentials jar from the mod list. I even tried installing WorldEdit on its own and it still works. What can I do to help with this?

**Comment by luacs1998** [comment]
This is the fastcraft crash I've seen 140623* times, either remove fastcraft or upgrade to FC test builds posted at the end of player's thread.

*I may be exaggerating.

**Comment by olee** [comment]
PS: There's also a big notice about it on http://ci.forgeessentials.com/job/FE/ and http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735

**Comment by shadowc** [comment]
Thank you for assisting me and sorry for the time wasted! :) I will try that!

**Comment by shadowc** [comment]
It works without FastCraft, bummer, I can't find the version 1.22 of it :( But thanks a lot to you!

**Comment by aschmois** [comment]
Fastcraft 1.22 ctest10 http://forum.industrial-craft.net/index.php?page=Thread&postID=189302#post189302

(!!!) Note: The alpha versions are known to cause incompatibility with other mods. If you're finding this issue now, look through the thread if the link does not have the download in it anymore. Player is not placing the test links on the main post.
