### ISSUE TITLE
Server crashing before I can even start it

### ISSUE THREAD

**Issue by xEdDantesx** [ForgeEssentials/ForgeEssentialsMain#1642]
Hi, I need help with my server crashing when I am trying to install forge essentials.  The server was fine before I tried installing essentials. Here are the logs
ials.core.preloader.FELaunchHandler
[01:42:09] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.co
mmon.launcher.FMLDeobfTweaker
[01:42:09] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.
launcher.FMLInjectionAndSortingTweaker
[01:42:09] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.
launcher.FMLInjectionAndSortingTweaker
[01:42:09] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:10] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certi
ficate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[01:42:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:10] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASM
TransformerClass:102]: Successfully Registered Transformer
[01:42:11] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:inject
Data:295]: [Micdoodle8Core]: Patching game...
[01:42:11] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:inject
Data:295]: [Micdoodle8Core]: Patching game...
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class com.forgeessentials.
core.preloader.FELaunchHandler
[01:42:11] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.4.3 Sour
ce=file:/C:/Users/Brian%20Loss/Desktop/New%20folder%20(3)/Servers/CrundeeCraft
_101/mods/forgeessentials-1.7.10-1.4.1.801-server.jar Env=SERVER
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\antlr-2.7.7.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\dom4j-1.6.1.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\h2-1.3.175.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\hibernate-commons-annotations-4.0.5.Final.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\hibernate-core-4.3.7.Final.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\hibernate-entitymanager-4.3.7.Final.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\hibernate-jpa-2.1-api-1.0.0.Final.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\jandex-1.1.0.Final.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\javassist-3.18.1-GA.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\jboss-logging-3.1.3.GA.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\jboss-logging-annotations-1.2.0.Beta1.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\jboss-transaction-api_1.2_spec-1.0.0.Final.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\mysql-connector-java-5.1.22.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\pircbotx-1.9.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:82]: [ForgeEssentials] Loaded library file C:\Users
\Brian Law\Desktop\New folder (3)\Servers\CrundeeCraft_101\ForgeEssentials\li
b\xml-apis-1.0.b2.jar
[01:42:11] [main/INFO] [STDOUT]: [com.forgeessentials.core.preloader.classloadin
g.FEClassLoader:runClassLoad:112]: [ForgeEssentials] Loaded 0 modules
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.
launcher.FMLDeobfTweaker
[01:42:11] [main/INFO] [STDOUT]: [cofh.asm.CoFHAccessTransformer:readMappingFile
:40]: Adding Accesstransformer map: CoFH_at.cfg
[01:42:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:12] [main/INFO] [malisiscore]: [MalisisCoreTransformer] Hook registered f
or net.minecraft.client.Minecraft
[01:42:12] [main/INFO] [malisiscore]: [MalisisCoreTransformer] Hook registered f
or net.minecraft.client.multiplayer.PlayerControllerMP
[01:42:12] [main/INFO] [malisiscore]: [ChunkBlockTransformer] Hook registered fo
r net.minecraft.world.chunk.Chunk
[01:42:12] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registere
d for net.minecraft.world.World
[01:42:12] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registere
d for net.minecraft.world.World
[01:42:12] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registere
d for net.minecraft.item.ItemBlock
[01:42:12] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registere
d for net.minecraft.network.NetHandlerPlayServer
[01:42:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relaunc
her.CoreModManager$FMLPluginWrapper
[01:42:12] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.co
mmon.launcher.TerminalTweaker
[01:42:12] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepower
ed.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[01:42:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.
launcher.TerminalTweaker
[01:42:12] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.as
m.mixin.MixinEnvironment$EnvironmentStateTweaker
[01:42:12] [main/INFO] [malisiscore]: Found hooks for net.minecraft.network.NetH
andlerPlayServer (nh)
[01:42:12] [main/INFO] [MobiusCore]: Current code is OBFUSCATED
[01:42:12] [main/INFO] [MobiusCore]: [MobiusCore] Found net.minecraft.world.Worl
dServer [ mt ] with checksum 809C9966D9959719D330E716BCA614B2
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in b ()V
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in b ()V
[01:42:12] [main/INFO] [MobiusCore]: Found cpw.mods.fml.common.FMLCommonHandler
with checksum F626A08BBC07AE3F7D88072FDFDAE36E
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in onPreServerTick ()V

[01:42:12] [main/INFO] [MobiusCore]: Successful injection in onPostServerTick ()
V
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in onPreWorldTick (Lah
b;)V
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in onPostWorldTick (La
hb;)V
[01:42:12] [main/INFO] [MobiusCore]: Switching injection mode to FORGE
[01:42:12] [main/INFO] [MobiusCore]: [MobiusCore] Found net.minecraft.world.Worl
d [ ahb ] with checksum B842EC784132866EFEC5CAD71366A37F
[01:42:12] [main/INFO] [MobiusCore]: Found World.updateEntities()...
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in h ()V
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in h ()V
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in h ()V
[01:42:12] [main/INFO] [MobiusCore]: Successful injection in h ()V
[01:42:13] [main/INFO] [MobiusCore]: Found World.<init> (Lazc;Ljava/lang/String;
Lahj;Laqo;Lqi;)V
[01:42:13] [main/INFO] [MobiusCore]: Successful injection in <init> (Lazc;Ljava/
lang/String;Lahj;Laqo;Lqi;)V
[01:42:13] [main/INFO] [MobiusCore]: Successful injection in <init> (Lazc;Ljava/
lang/String;Lahj;Laqo;Lqi;)V
[01:42:13] [main/INFO] [malisiscore]: Found hooks for net.minecraft.world.World
(ahb)
[01:42:13] [main/INFO] [RandomThingsCore]: Found World Class: net/minecraft/worl
d/World
[01:42:13] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:p
rintLog:1848]: Galacticraft successfully injected bytecode into: oi (4 / 4)
[01:42:13] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:p
rintLog:1848]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[01:42:13] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecra
ft.server.MinecraftServer}
[01:42:13] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:p
rintLog:1848]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[01:42:13] [main/INFO] [RandomThingsCore]: Found Item Class: net/minecraft/item/
Item
[01:42:14] [main/INFO] [RandomThingsCore]: Found Leave Class: net/minecraft/bloc
k/BlockLeavesBase
[01:42:14] [main/INFO] [malisiscore]: Found hooks for net.minecraft.item.ItemBlo
ck (abh)
[01:42:14] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:p
rintLog:1848]: Galacticraft successfully injected bytecode into: zc (1 / 1)
[01:42:14] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0
_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0
_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_72]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwra
pper-1.11.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrappe
r-1.11.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0
_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0
_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_72]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:43) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/util/FakePl
ayer
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class
:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.util.Fake
Player
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class
:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPla
yerMP
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_72]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0
_72]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:182) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class
:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityP
layerMP
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_72]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0
_72]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:182) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class
:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.player.Ent
ityPlayerMP de90c246 dr b656625f 3 1
        at fastcraft.asm.FastCraftTransformer.transform(F:251) ~[fastcraft-1.21.
jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchC
lassLoader.java:279) ~[launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:176) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_72]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0
_72]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:182) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
        at net.minecraft.item.Item.func_150900_l(Item.java:192) ~[adb.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class
:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1260)
~[MinecraftServer.class:?]
        ... 12 more
Press any key to continue . . .

**Comment by aschmois** [comment]
Install fastcraft 1.22 (alpha). You can find it under the fastcraft thread in one of the last few posts. Or remove it. Fastcraft 1.21 and lower is not compatible with FE.
