### ISSUE TITLE
IRC disconnects randomly and server freezes permanently upon reconnect attempt

### ISSUE THREAD

**Issue by LemonLake** [ForgeEssentials/ForgeEssentialsMain#1651]
I am having two bugs with IRC in version ForgeEssentials 1.7.10-1.4.1.797-server.

The first big regards the fact that the PircBot disconnects from my IRC server after some amount of time. The last time, it seemed to last around 45 minutes before crashing. This was the error:
```
16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: Waiting for mode response interrupted
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.pircbotx.Channel.getMode(Channel.java:133)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.pircbotx.Channel.getModeArgument(Channel.java:182)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.pircbotx.Channel.getChannelKey(Channel.java:239)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.pircbotx.PircBotX.shutdown(PircBotX.java:2872)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.pircbotx.PircBotX.shutdown(PircBotX.java:2833)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.pircbotx.InputThread.run(InputThread.java:115)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.InterruptedException
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.CountDownLatch.await(Unknown Source)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.pircbotx.Channel.getMode(Channel.java:127)
[16:40:07] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 5 more
```

The server is an InspIRCd server with Anope running on Windows 7 64bit, on localhost.

When I use the command `/ircbot reconnect` in attempt to resolve the issue, the server freezes permanently, causing all players to time out, and any signals sent to the process are ignored. I have to force quit the server. Nothing is logged.

Here are the server details, as provided by an unrelated previous crash report that I have since resolved:
```
<snip by olee: thanks for the details but in this case not needed and makes post a bit huge>
```

**Comment by luacs1998** [comment]
Show me your IRC configuration.

**Comment by LemonLake** [comment]
```
IRC {
        # List of priviliged users that can use more commands via the IRC bot
        S:admins <
            Lemmmmy
         >

        # If enabled, allows usage of bot commands
        B:allowCommands=true

        # If enabled, allows usage of MC commands through the bot (only if the IRC user is in the admins list)
        B:allowMcCommands=true

        # Bot name
        S:botName=TechnicServer

        # List of channels to connect to, together with the # character
        S:channels <
            #general
         >

        # Enable IRC interoperability?
        B:enable=true

        # Header for messages sent from IRC. Must contain one "%s"
        S:ircHeader=(§cIRC§r)<%s>  

        # Header for IRC events. Must NOT contain any "%s"
        S:ircHeaderGlobal=(§cIRC§r) 

        # Header for messages sent from MC to IRC. Must contain two "%s"
        S:mcHeader=<%s> %s

        # Delay between messages sent to IRC
        I:messageDelay=0

        # NickServ password
        S:nickPassword=HIDDEN

        # Server port
        I:port=6667

        # If enabled, ingame messages will be sent to IRC as well
        B:sendMessages=true

        # Server address
        S:server=irc.nuclearstorm.net

        # Server password
        S:serverPassword=

        # Show IRC events ingame (e.g., join, leave, kick, etc.)
        B:showEvents=true

        # Show game events in IRC (e.g., join, leave, death, etc.)
        B:showGameEvents=true

        # Show chat messages from IRC ingame
        B:showMessages=true

        # If set to true, sets connection to twitch mode
        B:twitchMode=false
    }
```

**Comment by LemonLake** [comment]
After a few days, it seems to be more reliable. I will keep you updated on any problems.

**Comment by luacs1998** [comment]
Can I close this in the meantime?

**Comment by LemonLake** [comment]
You may.
