### ISSUE TITLE
Internal Server Error on v1.4.2.834, possible NPE

### ISSUE THREAD

**Issue by Alaberti** [ForgeEssentials/ForgeEssentialsMain#1661]
I don't get a crash, but users are unable to login on a FRESH install of FE 1.4.2.834 and get an Internal Server Error. Running Forge 1492, fastcraft 1.22 ctest13, and I have both utilized a default install as well as modified the main.cfg in order to try and narrow down potential faults to no avail. 

Edit: Removing fastcraft changes nothing. Modlist can be found here: http://pastebin.com/iv0isCpZ.

The console displays the following, and it's all I have as there is no crash log:
````
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
28.07 16:15:38 [Server] INFO at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
28.07 16:15:38 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
28.07 16:15:38 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
28.07 16:15:38 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
28.07 16:15:38 [Server] INFO at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
28.07 16:15:38 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
28.07 16:15:38 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
28.07 16:15:38 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
28.07 16:15:38 [Server] INFO at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) [HandshakeCompletionHandler.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) [NetworkDispatcher.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) [NetworkDispatcher.class:?]
28.07 16:15:38 [Server] INFO at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) [oi.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) [FMLCommonHandler.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_484_ZonedPermissionHelper_playerLogin_PlayerLoggedInEvent.invoke(.dynamic) [?:?]
28.07 16:15:38 [Server] INFO at com.forgeessentials.permissions.core.ZonedPermissionHelper.playerLogin(ZonedPermissionHelper.java:481) [ZonedPermissionHelper.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
28.07 16:15:38 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_993_ProtectionEventHandler_playerChangedZoneEvent_PlayerChangedZone.invoke(.dynamic) ~[?:?]
28.07 16:15:38 [Server] INFO at com.forgeessentials.protection.ProtectionEventHandler.playerChangedZoneEvent(ProtectionEventHandler.java:582) ~[ProtectionEventHandler.class:?]
28.07 16:15:38 [Server] INFO at com.forgeessentials.util.PlayerInfo.setInventoryGroup(PlayerInfo.java:385) ~[PlayerInfo.class:?]
28.07 16:15:38 [Server] INFO java.lang.NullPointerException
28.07 16:15:38 [Server] Server thread/ERROR [FML]: Exception caught during firing event com.forgeessentials.util.events.PlayerChangedZone@47220b31:
28.07 16:15:38 [Multicraft] Alaberti ran command Message of the Day

**Comment by olee** [comment]
Relevant line is `at com.forgeessentials.util.PlayerInfo.setInventoryGroup(PlayerInfo.java:385)`.
Will check this later.

**Comment by Alaberti** [comment]
Thank you.

**Comment by Alaberti** [comment]
Seems the issue isn't quite resolved. Added RFTools and this issue reared up again. I was able to pull more info this time: http://pastebin.com/raw.php?i=c9UauDJj.

**Comment by luacs1998** [comment]
Try 961?

**Comment by Alaberti** [comment]
961 has the same issue.

**Comment by Alaberti** [comment]
Is there a way to temporarily bypass this issue in the configs, or I guess turn off the permission system via config?

**Comment by olee** [comment]
Oh you have a corrupted player save it seems (in `world/FEData/json/PlayerInfo`).
Latest version fixes these crashes as would deleting the corrupt file.

**Comment by Alaberti** [comment]
There we go! Good to go. Thanks!
