### ISSUE TITLE
Add error catching for invalid /tpa

### ISSUE THREAD

**Issue by LemonLake** [ForgeEssentials/ForgeEssentialsMain#1679]
Server crashed a while ago after the 20 second timeout when someone did an invalid tpa:
(note: Abelatox was not online)
```
[14:49:23] [Server thread/ERROR]: Couldn't process command: 'tpa Abelatox'
java.lang.NullPointerException
	at com.forgeessentials.util.output.ChatOutputHandler.sendMessage(ChatOutputHandler.java:57) ~[ChatOutputHandler.class:?]
	at com.forgeessentials.util.output.ChatOutputHandler.sendMessage(ChatOutputHandler.java:43) ~[ChatOutputHandler.class:?]
	at com.forgeessentials.util.questioner.QuestionData.sendQuestion(QuestionData.java:39) ~[QuestionData.class:?]
	at com.forgeessentials.util.questioner.Questioner.add(Questioner.java:34) ~[Questioner.class:?]
	at com.forgeessentials.util.questioner.Questioner.add(Questioner.java:40) ~[Questioner.class:?]
	at com.forgeessentials.util.questioner.Questioner.add(Questioner.java:45) ~[Questioner.class:?]
	at com.forgeessentials.teleport.CommandTPA.parse(CommandTPA.java:79) ~[CommandTPA.class:?]
	at com.forgeessentials.core.commands.ParserCommandBase.func_71515_b(ParserCommandBase.java:17) ~[ParserCommandBase.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[14:49:44] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_31]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_31]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_31]
	at com.forgeessentials.util.questioner.Questioner.tickStart(Questioner.java:80) ~[Questioner.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_239_Questioner_tickStart_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

Server also didn't start back up because it tried to do a backup after the world was unloaded, but that's unrelated.

**Comment by LemonLake** [comment]
Another thing to do is also to not place people who are offline in the autocomplete list.

**Comment by LemonLake** [comment]
Thank you very much!
