### ISSUE TITLE
Constant NPEs on server ticking

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1690]
(forgeessentials-1.7.10-1.4.2.854-server.jar)

this error comes every second after server start regardless if player are online or not...
is it for you or for other mods...again^^

edit:

3 GB logfiles now... any suggestions ?
````
[17:35:05] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@4c943167:
java.lang.NullPointerException
	at net.minecraft.server.management.UserListOps.func_152699_b(SourceFile:39) ~[oj.class:?]
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9) ~[oj.class:?]
	at net.minecraft.server.management.UserList.func_152692_d(SourceFile:85) ~[om.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_152596_g(ServerConfigurationManager.java:717) ~[oi.class:?]
	at com.forgeessentials.api.permissions.ServerZone.getAdditionalPlayerGroups(ServerZone.java:318) ~[ServerZone.class:?]
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:364) ~[ServerZone.class:?]
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.checkUserPermission(ZonedPermissionHelper.java:886) ~[ZonedPermissionHelper.class:?]
	at com.forgeessentials.protection.ProtectionEventHandler.playerInteractEvent(ProtectionEventHandler.java:318) ~[ProtectionEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_726_ProtectionEventHandler_playerInteractEvent_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:353) [mx.class:?]
	at thaumcraft.common.entities.ai.interact.AIUseItem.click(AIUseItem.java:158) [AIUseItem.class:?]
	at thaumcraft.common.entities.ai.interact.AIUseItem.func_75246_d(AIUseItem.java:99) [AIUseItem.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103) [uj.class:?]
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540) [sw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) [sw.class:?]
	at thaumcraft.common.entities.golems.EntityGolemBase.func_70636_d(EntityGolemBase.java:354) [EntityGolemBase.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) [sw.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:35:05] [Server thread/ERROR] [FML/]: Index: 2 Listeners:
[17:35:05] [Server thread/ERROR] [FML/]: 0: HIGHEST
[17:35:05] [Server thread/ERROR] [FML/]: 1: ASM: com.forgeessentials.util.selections.SelectionEventHandler@6ab41c4b playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 2: ASM: com.forgeessentials.protection.ProtectionEventHandler@672df58d playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 3: HIGH
[17:35:05] [Server thread/ERROR] [FML/]: 4: ASM: com.forgeessentials.compat.worldedit.CUIComms@5d00277e playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 5: NORMAL
[17:35:05] [Server thread/ERROR] [FML/]: 6: ASM: gregtech.common.GT_Server@7a2db523 onPlayerInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 7: ASM: chylex.hee.system.achievements.AchievementEvents@3f556ae1 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 8: ASM: chylex.hee.mechanics.misc.TempleEvents@66fa970c onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 9: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@3ecde8fa onPlayerClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 10: ASM: mods.railcraft.common.carts.MinecartHooks@5ac08454 onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 11: ASM: com.bluepowermod.event.BPEventHandler@4127e54a onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 12: ASM: com.cricketcraft.chisel.item.chisel.ChiselController@2d5829e onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 13: ASM: minetweaker.mc1710.ForgeEventHandler@11ace26 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 14: ASM: pneumaticCraft.common.semiblock.SemiBlockManager@4b5b69c8 onInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 15: ASM: pneumaticCraft.common.EventHandlerPneumaticCraft@30d92eb2 onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 16: ASM: pneumaticCraft.common.EventHandlerUniversalSensor@261bf098 onInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 17: ASM: appeng.parts.PartPlacement@5f4b18f1 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 18: ASM: tuhljin.automagy.lib.events.AutomagyEventHandler@10a22270 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 19: ASM: com.carpentersblocks.util.handler.EventHandler@460ad3af onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 20: ASM: li.cil.oc.integration.fmp.EventHandler$@c61ee0f playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 21: ASM: com.enderio.core.common.handlers.RightClickCropHandler@3f90a8e0 handleCropRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 22: ASM: com.rwtema.extrautils.EventHandlerServer@4dfb8598 angelBlockDestroy(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 23: ASM: com.forgeessentials.signtools.SignToolsModule@3b73b9f onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 24: ASM: logisticspipes.LogisticsEventListener@1d3f949b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 25: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@4af5c4cd onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 26: ASM: appeng.fmp.FMPEvent@3ebe9899 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 27: ASM: com.forgeessentials.commands.util.CommandsEventHandler@4ce78cc2 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 28: ASM: com.forgeessentials.afterlife.AfterlifeEventHandler@58a0241d playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 29: LOW
[17:35:05] [Server thread/ERROR] [FML/]: 30: ASM: codechicken.multipart.minecraft.EventHandler@139d1d7 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[17:35:05] [Server thread/ERROR] [FML/]: 31: LOWEST
[17:35:05] [Server thread/ERROR] [FML/]: 32: ASM: com.forgeessentials.commands.util.ModuleCommandsEventHandler@4b04c320 playerMoveEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V

**Comment by luacs1998** [comment]
Which build is this? I was under the impression it had been fixed by @olee...

**Comment by olee** [comment]
This should have definitely been fixed.
All functions used in the latest builds (which covers 854 as well) use functions that should even by definition not be able to return any null value. The only thing I imagine is that the build of FE used was not the mentioned build 854. Anyway I will still push a little commit to make this code a little bit easier.

@jogi01 Please try using `/feinfo` command to print the exact version info.

**Comment by jogi01** [comment]
Running ForgeEssentials 1.4.2.854-nightly

well, the error is now temporarily not thrown, i guess this had something to do with some thaumcraft golems, these are NPCs, i have to ask a player if he has killed these golems or not so i can give you more input
