### ISSUE TITLE
[1.8]FE + PixelMon cause crash on dedicated server

### ISSUE THREAD

**Issue by liach** [ForgeEssentials/ForgeEssentialsMain#1695]
Only on dedicated server.
It seems that there's some issue with the watchdog.
Btw there's another mixin issue, which there's an invalid shadow field.
```
[13:02:45] [Server thread/TRACE] [pixelmon/pixelmon]: Sending event FMLServerAboutToStartEvent to mod pixelmon
[13:02:45] [Server thread/TRACE] [pixelmon/pixelmon]: Sent event FMLServerAboutToStartEvent to mod pixelmon
[13:02:45] [Server thread/TRACE] [worldedit/worldedit]: Sending event FMLServerAboutToStartEvent to mod worldedit
[13:02:47] [Server thread/TRACE] [worldedit/worldedit]: Sent event FMLServerAboutToStartEvent to mod worldedit
[13:02:47] [Server thread/DEBUG] [mixin/]: Mixing entity.MixinEntityTracker_01 from mixins.forgeessentials.json into net.minecraft.entity.EntityTracker
[13:02:47] [Server thread/WARN] [mixin/]: Mixin failed applying mixins.forgeessentials.json:entity.MixinEntityTracker_01 -> net.minecraft.entity.EntityTracker: org.spongepowered.asm.mixin.transformer.InvalidMixinException Shadow field trackedEntityIDs was not located in the target class
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Shadow field trackedEntityIDs was not located in the target class
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.attachFields(MixinPreProcessor.java:222) ~[forgeessentials-1.8-1.8.0.24-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.attach(MixinPreProcessor.java:151) ~[forgeessentials-1.8-1.8.0.24-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.createContextFor(MixinPreProcessor.java:133) ~[forgeessentials-1.8-1.8.0.24-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:511) ~[forgeessentials-1.8-1.8.0.24-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189) ~[forgeessentials-1.8-1.8.0.24-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:594) ~[forgeessentials-1.8-1.8.0.24-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:566) [forgeessentials-1.8-1.8.0.24-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:402) [forgeessentials-1.8-1.8.0.24-server.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:104) [forgeessentials-1.8-1.8.0.24-server.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_45]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:112) [qt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:256) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:259) [po.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[13:02:47] [Server thread/INFO] [FML/]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@f8984e8)
[13:02:48] [Server thread/INFO] [FML/]: Loading dimension 1 (world) (net.minecraft.server.dedicated.DedicatedServer@f8984e8)
[13:02:48] [Thread-15/INFO] [ForgeEssentials/]: Listing files for backup of world 1
[13:02:48] [Server thread/INFO] [FML/]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@f8984e8)
[13:02:48] [Thread-16/INFO] [ForgeEssentials/]: Listing files for backup of world -1
[13:02:48] [Thread-17/DEBUG] [FML/]: Gathering id map for writing to world save world
[13:02:49] [Thread-17/INFO] [ForgeEssentials/]: Listing files for backup of world 0
[13:03:10] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStartingEvent to mod mcp
[13:03:10] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStartingEvent to mod mcp
[13:03:10] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStartingEvent to mod FML
[13:03:10] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStartingEvent to mod FML
[13:03:10] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStartingEvent to mod Forge
[13:03:10] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStartingEvent to mod Forge
[13:03:10] [Server thread/TRACE] [ForgeEssentials/ForgeEssentials]: Sending event FMLServerStartingEvent to mod ForgeEssentials
[13:03:10] [Server Watchdog/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:03:10] [Server Watchdog/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.asm.transformers.TerminalTransformer$ExitVisitor.checkAccess(TerminalTransformer.java:142)
[13:03:10] [Server Watchdog/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.asm.transformers.TerminalTransformer$ExitVisitor.runtimeHaltCalled(TerminalTransformer.java:125)
[13:03:10] [Server Watchdog/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.dedicated.ServerHangWatchdog.func_180248_a(SourceFile:91)
[13:03:10] [Server Watchdog/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.dedicated.ServerHangWatchdog.run(SourceFile:69)
[13:03:10] [Server Watchdog/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[13:03:10] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Error loading permissions: invalid path
[13:03:10] [Server thread/TRACE] [ForgeEssentials/ForgeEssentials]: Sent event FMLServerStartingEvent to mod ForgeEssentials
[13:03:10] [Server thread/TRACE] [pixelmon/pixelmon]: Sending event FMLServerStartingEvent to mod pixelmon
[13:03:10] [Server thread/TRACE] [pixelmon/pixelmon]: Sent event FMLServerStartingEvent to mod pixelmon
[13:03:10] [Server thread/TRACE] [worldedit/worldedit]: Sending event FMLServerStartingEvent to mod worldedit
[13:03:10] [Server thread/TRACE] [worldedit/worldedit]: Sent event FMLServerStartingEvent to mod worldedit
[13:03:10] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStartedEvent to mod mcp
[13:03:10] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStartedEvent to mod mcp
[13:03:10] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStartedEvent to mod FML
[13:03:10] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStartedEvent to mod FML
[13:03:10] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStartedEvent to mod Forge
[13:03:10] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStartedEvent to mod Forge
[13:03:10] [Server thread/TRACE] [ForgeEssentials/ForgeEssentials]: Sending event FMLServerStartedEvent to mod ForgeEssentials
[13:03:12] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Command gamemode registered twice
[13:03:12] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Command weather registered twice
[13:03:12] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Command worldborder registered twice
[13:03:12] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Command kill registered twice
[13:03:12] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Command help registered twice
[13:03:12] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Command alias ? of command help registered twice
[13:03:12] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Command enchant registered twice
[13:03:12] [Server thread/ERROR] [ForgeEssentials/ForgeEssentials]: Command time registered twice
[13:03:12] [Server thread/TRACE] [ForgeEssentials/ForgeEssentials]: Sent event FMLServerStartedEvent to mod ForgeEssentials
[13:03:12] [Server thread/TRACE] [pixelmon/pixelmon]: Sending event FMLServerStartedEvent to mod pixelmon
[13:03:12] [Server thread/TRACE] [pixelmon/pixelmon]: Sent event FMLServerStartedEvent to mod pixelmon
[13:03:12] [Server thread/TRACE] [worldedit/worldedit]: Sending event FMLServerStartedEvent to mod worldedit
[13:03:12] [Server thread/TRACE] [worldedit/worldedit]: Sent event FMLServerStartedEvent to mod worldedit
[13:03:20] [Timer-3/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:03:20] [Timer-3/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.asm.transformers.TerminalTransformer$ExitVisitor.checkAccess(TerminalTransformer.java:142)
[13:03:20] [Timer-3/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.asm.transformers.TerminalTransformer$ExitVisitor.runtimeHaltCalled(TerminalTransformer.java:125)
[13:03:20] [Timer-3/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.dedicated.ServerHangWatchdog$1.run(SourceFile:85)
[13:03:20] [Timer-3/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[13:03:20] [Timer-3/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by luacs1998** [comment]
Where exactly is the problem?

**Comment by liach** [comment]
My fault, actually a crash with a watchdog... Gist posted above.

**Comment by olee** [comment]
I already fixed it. There was a bug in one of the 1.8 Mixins.

**Comment by liach** [comment]
Fixed... Though the watchdog error is still there but it no longer crashes.

**Comment by olee** [comment]
Thats what I said :sweat:
