### ISSUE TITLE
Multiworld crash with `/mw create`

### ISSUE THREAD

**Issue by ariath** [ForgeEssentials/ForgeEssentialsMain#1697]
Hi all!

I have just started testing ForgeEssentials and i have noticed a crash when you creates a world.
The build i'm using right now is forgeessentials-1.8-1.8.0.26-server, and this is what i get when i do /mw create worldname:
````
[12:45:58] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[qt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:692) ~[MinecraftServer.class:?]
	... 4 more
````

This is the full crash log: https://gist.github.com/ariath/99ae99bc4dd760722ccc

See ya!

**Comment by olee** [comment]
I didn't check Multiworld on 1.8 yet so it does not really surprise me.
However as Multiworld is scheduled for an important patch because of #1613 anyway, this will be fixed after #1613 has been done.
