### ISSUE TITLE
/craft crashes

### ISSUE THREAD

**Issue by liach** [ForgeEssentials/ForgeEssentialsMain#1698]
[Gist] (https://gist.github.com/liach/ad4361565628d9964469)

*EDIT by olee: Extracted relevant log*
````
[07:24:31] [Server thread/FATAL] [FML/]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Ticking player
java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Ticking player
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164) [cyk.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:394) ~[qw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[rj.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[mg.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[mg.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_175701_a(World.java:216) ~[aqu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:831) ~[aqu.class:?]
	at net.minecraft.inventory.ContainerWorkbench.func_75145_c(SourceFile:74) ~[aio.class:?]
	at net.minecraftforge.event.entity.player.PlayerOpenContainerEvent.<init>(PlayerOpenContainerEvent.java:27) ~[PlayerOpenContainerEvent.class:?]
	at net.minecraftforge.common.ForgeHooks.canInteractWith(ForgeHooks.java:493) ~[ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:296) ~[ahd.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:340) ~[qw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[rj.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[mg.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[mg.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more
````

**Comment by olee** [comment]
What exactly did you do and when did the crash happen? Directly after using `/craft`? Or only after you tried using the crafting grid?

**Comment by ariath** [comment]
I have also experimented this bug.
The server crashes as soon you do /craft.

See ya!

**Comment by Psykrot** [comment]
Happened to me as well.

**Comment by olee** [comment]
Are you on 1.7.10 or 1.8?

**Comment by liach** [comment]
It seems this command create a invalid GUI instance, causing a failed tick.

**Comment by Psykrot** [comment]
This bug happened to me on 1.8

**Comment by ariath** [comment]
Same, in 1.8.

**Comment by olee** [comment]
@liach please always specify which version you are working with - 1.7.10 or 1.8
Will check this soon.

**Comment by olee** [comment]
Ok the crash is fixed, but the crafting GUI still does not open.

The lazy response: Stop using `/craft` and we will remove it.
Use some other mods for mobile crafting tables.

Long version:
Minecraft changed core code which checks if there is actually a crafting table in the world where the interface was opened. This makes this the whole thing very difficult and it will probably need a Mixin patch...

**Comment by olee** [comment]
Ok luckily this was easier than I feared. Fixed!

**Comment by liach** [comment]
:laughing: 
```
at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
```

**Comment by olee** [comment]
You really think I have the time to notice such small stuff? :sweat:

**Comment by liach** [comment]
Ok that'll be deleted
