### ISSUE TITLE
Error Mixin in 901

### ISSUE THREAD

**Issue by Riddler76** [ForgeEssentials/ForgeEssentialsMain#1717]
Hi,

I can't launch my game with the new version.
Error : 
java.lang.ClassNotFoundException: org.spongepowered.mixin.MixinTweaker
java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_51]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_51]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by olee** [comment]
Which version? 1.7.10 or 1.8?

**Comment by Riddler76** [comment]
1.7.10

**Comment by Binford2000** [comment]
I got this error too:

minecraft version: 1.7.10

with FE-1.7.10-1.4.3.901-client.jar: minecraft client crash:
(tested with and without magiclauncher)

[main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.mixin.MixinTweaker
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0]
    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0]
    at magic.launcher.Launcher.main(SourceFile:214) [MagicLauncher_1.3.1.jar:?]


without FE-1.7.10-1.4.3.901-client.jar:  minecraft client works.
Server with FE-1.7.10-1.4.3.901-server.jar works, but all blocks, plants,... breaks give no drops.
