### ISSUE TITLE
Exception thrown on server - java.util.IllegalFormatConversionException: d != net.minecraft.util.BlockPos

### ISSUE THREAD

**Issue by bslezak** [ForgeEssentials/ForgeEssentialsMain#1736]
In attempting to use `//fewand` and mark an area to create a zone, I continually get an exception thrown, details below. I queried the IRC channel and it was suggested I log this as an issue.

## Environment
* Windows server minecraft_server.1.8.jar
* Forge forge-1.8-11.14.3.1450-universal.jar
* Forge Essentials forgeessentials-1.8-1.8.3.35-server.jar

## Exception upon joining server
[12:02:17] [Playerlogger/WARN] [FML]: ============================================================
[12:02:17] [Playerlogger/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[12:02:17] [Playerlogger/WARN] [FML]: Offendor: antlr/Parser.panic()V
[12:02:17] [Playerlogger/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[12:02:17] [Playerlogger/WARN] [FML]: =============================================================`

## Exception upon using fewand on dirt
[12:02:20] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@25a4cd7e:
java.util.IllegalFormatConversionException: d != net.minecraft.util.BlockPos
	at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source) ~[?:1.8.0_60]
	at java.util.Formatter$FormatSpecifier.printInteger(Unknown Source) ~[?:1.8.0_60]
	at java.util.Formatter$FormatSpecifier.print(Unknown Source) ~[?:1.8.0_60]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_60]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_60]
	at java.lang.String.format(Unknown Source) ~[?:1.8.0_60]
	at com.forgeessentials.core.misc.Translator.format(Translator.java:32) ~[Translator.class:?]
	at com.forgeessentials.util.selections.SelectionEventHandler.playerInteractEvent(SelectionEventHandler.java:54) ~[SelectionEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_SelectionEventHandler_playerInteractEvent_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:120) [ForgeEventFactory.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180784_a(ItemInWorldManager.java:142) [qx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:526) [rj.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_180763_a(SourceFile:40) [ml.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) [ml.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
[12:02:20] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[12:02:20] [Server thread/ERROR] [FML]: 0: HIGHEST
[12:02:20] [Server thread/ERROR] [FML]: 1: ASM: com.forgeessentials.util.selections.SelectionEventHandler@4f7c384e playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:02:20] [Server thread/ERROR] [FML]: 2: ASM: com.forgeessentials.protection.ProtectionEventHandler@4260dd74 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:02:20] [Server thread/ERROR] [FML]: 3: ASM: com.forgeessentials.playerlogger.PlayerLoggerEventHandler@7cac7ecf playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:02:20] [Server thread/ERROR] [FML]: 4: NORMAL
[12:02:20] [Server thread/ERROR] [FML]: 5: ASM: com.forgeessentials.signtools.SignToolsModule@4c489500 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:02:20] [Server thread/ERROR] [FML]: 6: ASM: com.forgeessentials.afterlife.AfterlifeEventHandler@713dce76 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:02:20] [Server thread/ERROR] [FML]: 7: ASM: com.forgeessentials.teleport.CommandJump@53dc51fd playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:02:20] [Server thread/ERROR] [FML]: 8: LOWEST
[12:02:20] [Server thread/ERROR] [FML]: 9: ASM: com.forgeessentials.commands.util.ModuleCommandsEventHandler@7f8a712a playerMoveEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:02:20] [Server thread/ERROR] [FML]: 10: ASM: com.forgeessentials.playerlogger.PlayerLogger@34619596 playerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:02:20] [Server thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.util.IllegalFormatConversionException: d != net.minecraft.util.BlockPos
java.util.concurrent.ExecutionException: java.util.IllegalFormatConversionException: d != net.minecraft.util.BlockPos
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_60]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.util.IllegalFormatConversionException: d != net.minecraft.util.BlockPos
	at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source) ~[?:1.8.0_60]
	at java.util.Formatter$FormatSpecifier.printInteger(Unknown Source) ~[?:1.8.0_60]
	at java.util.Formatter$FormatSpecifier.print(Unknown Source) ~[?:1.8.0_60]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_60]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_60]
	at java.lang.String.format(Unknown Source) ~[?:1.8.0_60]
	at com.forgeessentials.core.misc.Translator.format(Translator.java:32) ~[Translator.class:?]
	at com.forgeessentials.util.selections.SelectionEventHandler.playerInteractEvent(SelectionEventHandler.java:54) ~[SelectionEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_SelectionEventHandler_playerInteractEvent_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:120) ~[ForgeEventFactory.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180784_a(ItemInWorldManager.java:142) ~[qx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:526) ~[rj.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_180763_a(SourceFile:40) ~[ml.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) ~[ml.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_60]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more

**Comment by bslezak** [comment]
Confirmed this fix removed the exception! Messages coming through now when using the fewand.
