### ISSUE TITLE
IRC Chatbot crash

### ISSUE THREAD

**Issue by etmoonshade** [ForgeEssentials/ForgeEssentialsMain#1749]
The following stack trace was left behind:
````
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.RuntimeException: Waiting for mode response interrupted
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at org.pircbotx.Channel.getMode(Channel.java:133)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at org.pircbotx.Channel.getModeArgument(Channel.java:182)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at org.pircbotx.Channel.getChannelKey(Channel.java:239)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at org.pircbotx.PircBotX.shutdown(PircBotX.java:2872)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at org.pircbotx.PircBotX.shutdown(PircBotX.java:2833)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at org.pircbotx.InputThread.run(InputThread.java:115)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.InterruptedException
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at org.pircbotx.Channel.getMode(Channel.java:127)
[12:40:40] [bot1-input/INFO] [STDERR/ForgeEssentials]: [java.lang.Throwable$WrappedPrintStream:println:748]:    ... 5 more
````

I have literally zero context for this. No IRC network problems at the time (I'm an oper there,) one player online at the time (not talking,) and nobody talking on the IRC channel at the time.

I can give a pastebin of the logs if requested, but there's nothing other than "[12:31:09] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save rcfworld20150822-2" in there since the last time it was known working (talking with an online player on IRC.)

**Comment by olee** [comment]
Looks like just a network issue to me.
Maybe you had some connection loss from your server to the IRC server.
If you can't replicate it, it probably doesn't matter.

For the record: What happened after that error? Did the server crash or did it just keep running only with IRC not working?

**Comment by etmoonshade** [comment]
Minecraft server was running just fine after that crash, although I rebooted it as a precautionary measure - I -do- have a memory leak problem somewhere, but haven't seen problems in the past until FE starts giving me the 90+% memory warnings.

**Comment by luacs1998** [comment]
This sounds the same as #1752 - closing.

**Comment by etmoonshade** [comment]
If it makes a difference in your troubleshooting: Roughly the same stack trace as #1752, different circumstances - my server wasn't shutting down at the time, wasn't out of memory, and it didn't crash after the error in the bot.

I don't particularly object to the closing since the bug didn't really worry me, but I just wanted to make sure you're not going off poorly-worded info on my part. :)

**Comment by luacs1998** [comment]
Thanks for the additional info - but yeah will look into it.
