### ISSUE TITLE
Malisisdoors Mixin incompatibility

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1761]
Posted by olagarde on IRC
````
java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/PlayerControllerMP
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:340)
        at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
        at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
        at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
        at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.PlayerControllerMP
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 35 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:638)
        at java.util.ArrayList.remove(ArrayList.java:477)
        at net.malisis.core.asm.AsmHook.walkSteps(AsmHook.java:131)
        at net.malisis.core.asm.MalisisClassTransformer.transform(MalisisClassTransformer.java:80)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
        ... 37 more
````

**Comment by liach** [comment]
Actually malisiscore. Almura is already facing this situation like mentioned [here] (https://github.com/SpongePowered/Mixin/issues/63#issuecomment-133024195).

**Comment by olee** [comment]
Any idea @Mumfrey?
Afaik we use the latest Mixin so I don't think (hope) we do anything wrong...

**Comment by olagarde** [comment]
Right you are sir, or so it would appear.  Updated malisiscore from 0.10.2 to 0.12.9 and malisisdoors from 1.7.10-1.3.1 to 1.7.10-1.10.  Still working through my test matrix but at the point of previous failure FML now sez:  

[23:11:16] [Client thread/INFO] [malisiscore]: Found hooks for net.minecraft.client.multiplayer.PlayerControllerMP (bje)

which isn't "classdef where is ye", so: progress!

**Comment by liach** [comment]
So you mean that newest malisiscore works with newest forgeessentials? That is perfect!

**Comment by olagarde** [comment]
Looks that way -- don't see a specific mention in the malisiscore changelog but updating to 0.12.6+ works with the FE 1.4.3.958 build.  Client-side tests ran clean, confirm/close, thx!
